// Interface text in English (en), Marathi (mr) and Hindi (hi). Placeholders: {name}.
// An entry can be { one, other } for counts; `n` picks the form.
// Trade words follow the research: case = पेटी, credit = उधार / उधारी, scheme = स्कीम, route = रूट.
// Values under tier. ch. shop. cat. area. region. repRole. role. schOffer. schExtras. translate data values.

import { FIELD_EN } from './feature/strings-en.js';
import { FIELD_MR } from './feature/strings-mr.js';
import { FIELD_HI } from './feature/strings-hi.js';

export const STRINGS = {
  en: {
    'common.back': 'Back',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.clear': 'Clear',
    'common.language': 'Language',
    'common.chooseLanguage': 'Choose a language',
    'common.today': 'today',
    'common.yesterday': 'yesterday',
    'common.tomorrow': 'tomorrow',
    'common.daysAgo': '{n} days ago',
    'common.inDays': 'in {n} days',
    'common.ongoing': 'Ongoing',
    'common.till': 'Till {date}',
    'common.and': 'and',

    'unit.case': 'case',
    'unit.crate': 'crate',
    'n.case': { one: '{n} case', other: '{n} cases' },
    'n.crate': { one: '{n} crate', other: '{n} crates' },
    'n.freeCase': { one: '{n} free case', other: '{n} free cases' },
    'n.outlet': { one: '{n} outlet', other: '{n} outlets' },
    'n.order': { one: '{n} order', other: '{n} orders' },
    'n.line': { one: '{n} line', other: '{n} lines' },
    'n.visitsMonth': { one: '{n} visit a month', other: '{n} visits a month' },
    'n.visitsShort': '{n}×/month',
    'n.function': { one: '{n} function', other: '{n} functions' },
    'pack.PET': 'bottles',
    'pack.glass': 'bottles',
    'pack.can': 'cans',
    'pack.tetra': 'packs',
    'pack.units': 'units',

    'demo.tag': 'Demo',
    'demo.reset': 'Reset demo',
    'demo.stub': 'Stub',
    'demo.resetTitle': 'Reset the demo?',
    'demo.resetBody': 'This deletes the {orders} saved during this demo and signs you out.',
    'demo.resetBodyNone': 'No orders saved yet. This signs you out and starts the demo again.',
    'demo.resetNote': 'It also clears today\'s clock-in, notes and issues recorded in this browser. Past orders in the data files are not touched.',
    'demo.resetDone': 'Demo reset. Saved orders cleared.',
    'fatal.served': "Couldn't load the demo data",
    'fatal.local': 'This page has no data inside it',
    'fatal.servedHelp': 'Check that the data/ folder sits next to this page, with every file listed in the data contract, and that each file is valid JSON.',
    'fatal.localHelp': 'Open gt-app.html (the single-file version, which carries its data inside), or open the hosted link.',

    'login.eyebrow': 'Field sales · {region}',
    'login.proto': 'prototype',
    'login.lede': "Sign in to open today's route for {distributor}.",
    'login.username': 'Username',
    'login.usernamePh': 'Your name',
    'login.password': 'Password',
    'login.errUser': 'Enter a username',
    'login.errPass': 'Enter a password',
    'login.submit': 'Sign in',
    'login.hint': 'Any username and password works. Your username is shown as the rep’s name.',
    'login.demoDate': 'Demo date',

    'home.title': 'Today',
    'home.allOutlets': 'All outlets',
    'home.hi': 'Hi, {name}',
    'home.today': '{outlets} today',
    'home.visited': '{n} visited',
    'home.routeDone': 'Route done',
    'home.progress': 'Outlets visited',
    'home.orders': 'Orders',
    'home.cases': 'Cases',
    'home.value': 'Value',
    'home.shownOf': "The prototype shows {shown} of the {total} outlets on today's route.",
    'home.route': "Today's route · {region}",
    'home.noRoute': "No outlets on today's route",
    'home.noRouteBody': 'Open the outlet list to find any outlet.',
    'home.seeAll': 'See all outlets',
    'status.toVisit': 'To visit',
    'status.saved': 'Order saved · {cases} · {value}',
    'status.savedN': '{n} orders saved · {cases} · {value}',
    'status.inProgress': 'Order in progress · {cases}',
    'status.savedShort': 'Order saved',
    'status.savedShortN': '{n} orders saved',

    'outlets.title': 'All shops',
    'outlets.search': 'Search name, area or channel',
    'outlets.searchLabel': 'Search outlets',
    'outlets.filters': 'Filter outlets',
    'outlets.all': 'All',
    'outlets.route': "Today's route",
    'outlets.count': '{shown} of {total}',
    'outlets.noMatch': 'No outlet matches “{q}”',
    'outlets.noMatchAll': 'Check the spelling, or search by area or channel.',
    'outlets.noMatchFilter': 'Try another filter, or clear the search.',
    'outlets.clearSearch': 'Clear search',
    'outlets.noneInFilter': 'No outlets in this filter',
    'outlets.showAll': 'Show all outlets',
    'outlets.notOnRoute': "Not on today's route",
    'persona.tag': 'Demo · Persona {no} · {label}',
    'persona.tip': 'Demo aid: the persona this outlet stands for',

    'outlet.title': 'Shop details',
    'outlet.stop': "Today's route · stop {n}",
    'outlet.owner': 'Owner',
    'outlet.directions': 'Directions',
    'outlet.directionsLabel': 'Directions to {name} in Google Maps (opens in a new tab)',
    'outlet.savedToday': 'Order saved today',
    'outlet.savedTodayN': '{n} orders saved today',
    'outlet.closed': 'Closed {range}',
    'outlet.closedStarts': 'starts {rel}',
    'outlet.closedNow': 'closed now',
    'outlet.book': 'Book order',
    'outlet.bookAnother': 'Book another order',
    'outlet.continue': 'Continue order · {cases}',
    'outlet.notFound': 'Outlet not found',
    'outlet.notFoundBody': 'There is no outlet with the ID “{id}” in the data.',
    'outlet.openList': 'Open the outlet list',
    'card.lastOrder': 'Last order and visit',
    'kv.lastOrder': 'Last order',
    'kv.cases': 'Cases',
    'kv.value': 'Value',
    'kv.lastVisit': 'Last visit',
    'kv.nextVisit': 'Next visit',
    'kv.noOrders': 'No orders yet',
    'kv.noVisits': 'No visits yet',
    'kv.minutes': '{n} min',
    'kv.plusFree': '+ {n} free',
    'card.payment': 'Payment',
    'kv.creditLimit': 'Credit limit',
    'kv.outstanding': 'Outstanding',
    'kv.overdue': 'Overdue',
    'kv.overdueAmt': '{amt} overdue',
    'kv.lastPayment': 'Last payment',
    'kv.noneYet': 'None yet',
    'card.schemes': 'Schemes',
    'scheme.applicable': 'Applicable',
    'scheme.enrolled': 'Enrolled',
    'scheme.usedUp': '{used} of {cap} used',
    'scheme.usesTaken': '{used} of {cap} uses taken in {month}',
    'scheme.none': 'No schemes running today',
    'scheme.legend': 'Enrolled: already receiving it. Applicable: can be used on an order. Tap a scheme for details.',
    'card.history': 'Order history',
    'history.last': { one: 'Last order', other: 'Last {n} orders' },
    'history.since': '{orders} since {date}.',
    'history.empty': 'No orders yet',
    'history.emptyBody': 'This outlet has not ordered with us yet. Its first order will show here.',
    'history.strip': 'Cases per month, {from} – {to}. {month} is only to {date}.',
    'history.stripAria': 'Cases per month.',
    'card.cooler': 'Cooler',
    'cooler.label': 'Cooler',
    'cooler.company': 'Company cooler · {count} × {litres} L',
    'cooler.lastAudit': 'Last audit',
    'cooler.onlyOurs': 'Only our drinks',
    'cooler.yes': 'Yes',
    'cooler.otherBrands': 'No, other brands inside',
    'cooler.fillTemp': 'Fill · temperature',
    'cooler.warm': '{t}°C (above 6°C)',
    'cooler.noAudit': 'No audit yet',
    'cooler.outage': 'Afternoon power cuts: the cooler warms up.',
    'cooler.ownFridge': 'Own fridge',
    'cooler.iceBox': 'Own ice box',
    'cooler.none': 'No cooler · sells from the shelf',
    'cooler.crates': 'Empty crates held',
    'card.bookings': 'Upcoming bookings',
    'bookings.next': 'Next 3 of {n} bookings till {date} · ~{cases} in all.',
    'bookings.note': "Recorded by the rep from the outlet's calendar. Case counts are estimates.",
    'card.notes': 'Visit notes',
    'notes.empty': 'No notes yet',

    'sch.chip.free': 'Buy {buy}, get {free} free',
    'sch.chip.mix': ' · mix',
    'sch.chip.pct': '{pct}% off at {min}+ cases',
    'sch.chip.first': '{pct}% off first order',
    'sch.offer.freePooled': 'Buy {buy} cases, get {free} free. Any mix of {skus} counts.',
    'sch.offer.free': 'Buy {buy} cases of {skus}, get {free} free.',
    'sch.offer.pct': '{pct}% off {skus} when they add up to {min} cases or more.',
    'sch.offer.first': '{pct}% off the whole first order, for outlets in their first {days} days.',
    'sch.reason.dates': 'Outside scheme dates',
    'sch.reason.tier': 'Not for {tier}',
    'sch.reason.cooler': 'Needs a company cooler',
    'sch.reason.age': 'Only for outlets in their first {days} days',
    'sch.reason.first': 'First order only',

    'book.title': 'New order',
    'book.search': 'Search products',
    'book.category': 'Category',
    'book.all': 'All',
    'book.firstOrder': '{name}: {offer} for this outlet.',
    'book.review': 'Review',
    'book.cartEmpty': 'Cart is empty',
    'book.noScheme': 'No scheme applied yet',
    'book.off': '{amt} off',
    'book.noMatch': 'No product matches “{q}”',
    'book.noMatchIn': 'Nothing in {cat}. Try All.',
    'book.noMatchBody': 'Try a flavour, a pack size or a code.',
    'book.noneIn': 'No products in {cat}',
    'book.rate': '{rate} / {unit}',
    'book.deposit': ' + deposit',
    'book.mrp': 'MRP {mrp}',
    'book.returnable': 'returnable',
    'book.fewer': 'One {unit} fewer of {name}',
    'book.more': 'One more {unit} of {name}',
    'book.qty': 'Number of {unit}s of {name}',
    'book.hintWhole': 'Whole cases only',
    'book.hintMax': '{max} cases max',
    'book.capUsed': '{chip} · {cap} of {cap} used in {month}',
    'book.chipAdd': 'Add {n} {unit}s of {name} for {scheme}',
    'book.added': 'Added {cases} of {name} · {scheme}',
    'book.openTitle': 'Another order is still open',
    'book.openBody': '{name} has {cases} that are not submitted yet.',
    'book.choose': 'Choose what to do',
    'book.unsavedTitle': 'Unsaved order',
    'book.unsavedBody': "{name} has an order that isn't submitted yet: {cases} · {value}.",
    'book.unsavedQ': 'Keep editing it, or discard it and start a new order for {name}?',
    'book.keep': 'Keep editing {name}',
    'book.discard': 'Discard it and start here',

    'review.title': 'Order summary',
    'review.delivery': 'Delivery {date} · {rel}',
    'review.qtyRate': '{qty} × {rate}',
    'review.free': '+{n} free expected · {name}',
    'review.edit': 'Edit order',
    'review.editShort': 'Edit',
    'review.schemes': 'Schemes on this order',
    'review.totals': 'Totals',
    'review.gross': 'Gross',
    'review.discounts': 'Discounts',
    'review.net': 'Net',
    'review.totalCases': 'Total cases',
    'review.paidFree': '({paid} paid + {free} free)',
    'review.submit': 'Submit order · {net}',
    'review.booked': 'Order value',
    'review.estTitle': 'Scheme estimate · not applied now',
    'review.estFree': 'Free cases expected',
    'review.estOff': 'Estimated discount',
    'review.estNote': 'Schemes are settled later by the distributor. The retailer is billed the order value; the benefit follows in the claim.',
    'book.estFree': 'est. {free} later',
    'book.estOff': 'est. {amt} off later',
    'review.saving': 'Saving…',
    'review.toast': 'Order saved for {name}',
    'review.nothing': 'Nothing to review yet',
    'review.nothingBody': "Add products to {name}'s order first.",
    'review.goBook': 'Go to booking',
    'rn.off': '{name} · {reason}',
    'rn.free': '{name}: +{free} as {sku}',
    'rn.cap': ' · {used} of {cap} uses this month',
    'rn.capReached': '. Monthly cap reached.',
    'rn.capFull': '{name}: {used} of {cap} uses this month, no free case',
    'rn.pct': '{name}: {pct}% off · {amt}',
    'rn.pctFirst': '{name}: {pct}% off the first order · {amt}',

    'saved.title': 'Order placed',
    'saved.gone': 'This order is no longer saved',
    'saved.goneBody': 'The demo may have been reset.',
    'saved.order': 'Order',
    'saved.cases': 'Cases',
    'saved.lines': 'Lines',
    'saved.discounts': 'Discounts',
    'saved.net': 'Net',
    'saved.delivery': 'Delivery',
    'saved.backRoute': 'Back to route',
    'saved.list': 'Outlet list',
    'saved.view': 'View {name}',

    'sd.title': 'Scheme',
    'sd.notFound': 'Scheme not found',
    'sd.notFoundBody': 'There is no scheme with the ID “{id}”.',
    'sd.st.applicable': 'Applicable at {outlet}',
    'sd.st.enrolled': '{outlet} is enrolled',
    'sd.st.used': 'Used up for {month} at {outlet}',
    'sd.st.not': 'Not applicable at {outlet}',
    'sd.st.applicableBody': 'It can be used on the next order.',
    'sd.st.enrolledBody': 'The outlet is already receiving this benefit.',
    'sd.st.usedBody': 'All {cap} free cases for this month are used. It works again from {date}.',
    'sd.offer': 'The offer',
    'sd.details': 'Details',
    'sd.type': 'Type',
    'sd.type.free-goods': 'Free cases',
    'sd.type.percent-off': 'Discount',
    'sd.type.first-order': 'First-order discount',
    'sd.type.program': 'Monthly program',
    'sd.valid': 'Valid',
    'sd.daysLeft': { one: '{n} day left', other: '{n} days left' },
    'sd.who': 'Who can get it',
    'sd.tiers': '{tiers} outlets',
    'sd.allOutlets': 'All outlets',
    'sd.coolerOnly': 'Outlets with a company cooler',
    'sd.firstDays': 'Outlets in their first {days} days',
    'sd.limit': 'Monthly limit',
    'sd.limitVal': '{cap} free cases per outlet',
    'sd.used': 'Used in {month}',
    'sd.usedVal': '{used} of {cap}',
    'sd.freeAs': 'Free case given as',
    'sd.freeLargest': 'The product with the most cases in the order',
    'sd.freeSame': 'The same product',
    'sd.paid': 'How it is paid',
    'sd.pay.free-goods': 'The free case comes with the delivery',
    'sd.pay.percent-off': 'Taken off the invoice',
    'sd.pay.first-order': 'Taken off the invoice',
    'sd.pay.program': 'Paid every month',
    'sd.also': 'Also',
    'sd.products': 'Products',
    'sd.perShop': 'per shop a month',
    'sd.firstShort': 'New shops, first {days} days',
    'sd.coolerShort': 'cooler shops',
    'sd.timesUsed': 'Times used',
    'sd.freeGot': 'Free cases got',
    'sd.lastUsed': 'Last used',
    'sd.offerFree': 'Buy {buy} cases, get {free} free case.',
    'sd.offerPct': 'Buy {min} or more cases, get {pct}% off.',
    'sd.history': 'Used at this outlet',
    'sd.historyEmpty': 'Not used here yet',
    'sd.historyApplied': 'Applied',
    'sd.why': 'Why not',
    'sd.audit': 'Last cooler audit',
    'sd.book': 'Book with this scheme',
    'sd.backOutlet': 'Back to outlet',

    'tp.title': 'Talking points',
    'tp.sub': 'Tap a point to see more',
    'tp.forYou': 'For you only',
    'tp.forYouNote': 'Don’t show the owner',
    'tp.more': { one: 'Show 1 more', other: 'Show {n} more' },
    'tp.less': 'Show less',
    'tp.open': 'Talking points · {n}',
    'tp.none': 'Nothing special to raise at this visit.',
    'tp.f.ly': 'same days last year',
    'tp.f.recent': 'past {days} days this year',
    'tp.f.topPacks': 'Top packs last year',
    'tp.f.till': 'valid till',
    'tp.f.firstTill': 'welcome offer till',
    'tp.f.freeLeft': 'free cases left this month',
    'tp.f.anyMix': 'Any mix of these counts',
    'tp.f.together': 'These count together',
    'tp.f.pack': 'Pack',
    'tp.seeScheme': 'See scheme',
    'tp.cat.weather': 'Weather',
    'tp.cat.history': 'Last year',
    'tp.cat.event': 'Coming up',
    'tp.cat.bookings': 'Bookings',
    'tp.cat.scheme': 'Scheme',
    'tp.cat.stock': 'Stock',
    'tp.cat.cooler': 'Cooler',
    'tp.cat.payment': 'Payment',
    'tp.cat.peers': 'Nearby shops',
    'tp.cat.closure': 'Closure',
    'tp.cat.empties': 'Empties',
    'tp.src.forecast': 'Forecast of {date}',
    'tp.src.orders': 'Your orders',
    'tp.src.calendar': 'Local calendar',
    'tp.src.bookings': 'Booking calendar',
    'tp.src.stock': 'Distributor stock, {date}',
    'tp.src.scheme': 'Scheme terms',
    'tp.src.audit': 'Cooler audit, {date}',
    'tp.src.peers': '{n} similar shops',
    'tp.src.account': 'Account',
    'tp.heat.title': 'Hot and dry until {date}: {min}–{max}°C, no rain',
    'tp.heat.titleShower': 'Hot until {date}: {min}–{max}°C, a stray shower possible',
    'tp.heat.chilled': 'Cold small bottles sell fastest in this heat. Rain usually starts around {onset}.',
    'tp.heat.takehome': 'Families buy more big bottles and water in this heat. Rain usually starts around {onset}.',
    'tp.ly.title': 'Same {days} days last year: {cases} sold',
    'tp.ly.body': 'Past {days} days this year: {recent} sold. Top packs last year: {skus}.',
    'tp.ly.bodyNoRecent': 'Top packs last year: {skus}.',
    'tp.closure.title': 'Closed {range}',
    'tp.closure.soon': { one: 'Only 1 selling day between tomorrow’s delivery and the break. Order just enough to finish the stock.', other: 'Only {n} selling days between tomorrow’s delivery and the break. Order just enough to finish the stock.' },
    'tp.closure.now': 'Closed now; reopens {date}.',
    'tp.bookings.title': '{functions} before the next visit: ~{cases}',
    'tp.bookings.body': 'Biggest: {date}, {event}.',
    'tp.event.up': 'Usually lifts sales here, by about {pct}.',
    'tp.event.down': 'Usually slows sales here.',
    'tp.event.packs': ' Mostly {packs}.',
    'tp.scheme.left': '{left} of {cap} free cases left this month. Any mix of {skus} counts.',
    'tp.scheme.leftSingle': '{left} of {cap} free cases left this month.',
    'tp.scheme.usedTitle': '{name}: used up for {month}',
    'tp.scheme.nextMonth': 'All {cap} free cases for {month} are used. The order on the next visit ({date}) earns free cases again.',
    'tp.scheme.pct': 'Counts {skus} together. Valid till {date}.',
    'tp.scheme.till': 'Valid till {date}.',
    'tp.scheme.first': 'Welcome offer for new outlets, valid till {date}.',
    'tp.stock.rationed': '{sku}: at most {max} cases per order',
    'tp.stock.out': '{sku} is out at the distributor',
    'tp.stock.body': 'From the stock report of {date}; it may have changed.',
    'tp.stock.alt': ' Offer {alt} instead.',
    'tp.peers.title': 'Similar shops nearby sell about {n} cases a week',
    'tp.peers.body': 'Mostly {skus}.',
    'tp.cooler.fixTitle': 'Cooler was {fill}% full at {temp}°C on {date}',
    'tp.cooler.warm': 'Drinks above 6°C sell slower: keep it switched on and closed.',
    'tp.cooler.fill': 'A full cooler sells more: fill it before the afternoon rush.',
    'tp.cooler.outage': ' Afternoon power cuts here: load it in the morning.',
    'tp.cooler.rewardTitle': 'Cooler reward: {amt} this month',
    'tp.cooler.rewardBody': 'Keep only our drinks inside for the next photo audit.',
    'tp.empties.title': 'Keep {n} empty crates ready',
    'tp.empties.body': 'Glass is delivered only against empties, crate for crate.',
    'tp.pay.overdue': '{amt} overdue',
    'tp.pay.overdueBody': 'Credit left today: {left}. Last payment {date}.',
    'tp.pay.cash': 'Credit up to {limit}; anything above is cash',
    'tp.pay.cashBody': 'Agree the cash and credit split before booking a big order.',
  },

  mr: {
    'common.back': 'मागे',
    'common.close': 'बंद करा',
    'common.cancel': 'रद्द करा',
    'common.clear': 'पुसा',
    'common.language': 'भाषा',
    'common.chooseLanguage': 'भाषा निवडा',
    'common.today': 'आज',
    'common.yesterday': 'काल',
    'common.tomorrow': 'उद्या',
    'common.daysAgo': '{n} दिवसांपूर्वी',
    'common.inDays': '{n} दिवसांनी',
    'common.ongoing': 'सतत सुरू',
    'common.till': '{date} पर्यंत',
    'common.and': 'आणि',

    'unit.case': 'पेटी',
    'unit.crate': 'क्रेट',
    'n.case': { one: '{n} पेटी', other: '{n} पेट्या' },
    'n.crate': { one: '{n} क्रेट', other: '{n} क्रेट' },
    'n.freeCase': { one: '{n} मोफत पेटी', other: '{n} मोफत पेट्या' },
    'n.outlet': { one: '{n} दुकान', other: '{n} दुकाने' },
    'n.order': { one: '{n} ऑर्डर', other: '{n} ऑर्डर' },
    'n.line': { one: '{n} ओळ', other: '{n} ओळी' },
    'n.visitsMonth': { one: 'महिन्याला {n} भेट', other: 'महिन्याला {n} भेटी' },
    'n.visitsShort': '{n}×/महिना',
    'n.function': { one: '{n} कार्यक्रम', other: '{n} कार्यक्रम' },
    'pack.PET': 'बाटल्या',
    'pack.glass': 'बाटल्या',
    'pack.can': 'कॅन',
    'pack.tetra': 'पॅक',
    'pack.units': 'नग',

    'demo.tag': 'डेमो',
    'demo.reset': 'डेमो रीसेट',
    'demo.stub': 'स्टब',
    'demo.resetTitle': 'डेमो रीसेट करायचा?',
    'demo.resetBody': 'या डेमोत सेव्ह केलेल्या {orders} हटवल्या जातील आणि तुम्ही साइन आउट व्हाल.',
    'demo.resetBodyNone': 'अजून एकही ऑर्डर सेव्ह नाही. तुम्ही साइन आउट व्हाल आणि डेमो पुन्हा सुरू होईल.',
    'demo.resetNote': 'डेटा फाइलमधील जुन्या ऑर्डर तशाच राहतील.',
    'demo.resetDone': 'डेमो रीसेट झाला. सेव्ह केलेल्या ऑर्डर हटवल्या.',
    'fatal.served': 'डेमो डेटा लोड झाला नाही',
    'fatal.local': 'या पेजमध्ये डेटा नाही',
    'fatal.servedHelp': 'data/ फोल्डर या पेजशेजारी आहे, डेटा करारातील सर्व फाइल आहेत आणि प्रत्येक फाइल योग्य JSON आहे, हे तपासा.',
    'fatal.localHelp': 'gt-app.html उघडा (एक-फाइल आवृत्ती, ज्यात डेटा आतच आहे), किंवा होस्ट केलेली लिंक उघडा.',

    'login.eyebrow': 'फील्ड सेल्स · {region}',
    'login.proto': 'प्रोटोटाइप',
    'login.lede': '{distributor} साठी आजचा रूट उघडण्यासाठी साइन इन करा.',
    'login.username': 'युजरनेम',
    'login.usernamePh': 'तुमचे नाव',
    'login.password': 'पासवर्ड',
    'login.errUser': 'युजरनेम लिहा',
    'login.errPass': 'पासवर्ड लिहा',
    'login.submit': 'साइन इन करा',
    'login.hint': 'कोणतेही युजरनेम आणि पासवर्ड चालेल. तुमचे युजरनेम सेल्स रेपचे नाव म्हणून दिसेल.',
    'login.demoDate': 'डेमो तारीख',

    'home.title': 'आज',
    'home.allOutlets': 'सर्व दुकाने',
    'home.hi': 'नमस्कार, {name}',
    'home.today': 'आज {outlets}',
    'home.visited': 'भेटी पूर्ण: {n}',
    'home.routeDone': 'रूट पूर्ण',
    'home.progress': 'भेट दिलेली दुकाने',
    'home.orders': 'ऑर्डर',
    'home.cases': 'पेट्या',
    'home.value': 'मूल्य',
    'home.shownOf': 'आजच्या रूटवरील {total} पैकी {shown} दुकाने प्रोटोटाइपमध्ये दाखवली आहेत.',
    'home.route': 'आजचा रूट · {region}',
    'home.noRoute': 'आजच्या रूटवर एकही दुकान नाही',
    'home.noRouteBody': 'कोणतेही दुकान शोधण्यासाठी दुकानांची यादी उघडा.',
    'home.seeAll': 'सर्व दुकाने पहा',
    'status.toVisit': 'भेट बाकी',
    'status.saved': 'ऑर्डर सेव्ह · {cases} · {value}',
    'status.savedN': '{n} ऑर्डर सेव्ह · {cases} · {value}',
    'status.inProgress': 'ऑर्डर सुरू · {cases}',
    'status.savedShort': 'ऑर्डर सेव्ह',
    'status.savedShortN': '{n} ऑर्डर सेव्ह',

    'outlets.title': 'सर्व दुकाने',
    'outlets.search': 'नाव, भाग किंवा प्रकार शोधा',
    'outlets.searchLabel': 'दुकाने शोधा',
    'outlets.filters': 'दुकाने फिल्टर करा',
    'outlets.all': 'सर्व',
    'outlets.route': 'आजचा रूट',
    'outlets.count': '{total} पैकी {shown}',
    'outlets.noMatch': '“{q}” शी जुळणारे दुकान नाही',
    'outlets.noMatchAll': 'स्पेलिंग तपासा किंवा भाग/प्रकारानुसार शोधा.',
    'outlets.noMatchFilter': 'दुसरा फिल्टर वापरा किंवा शोध पुसा.',
    'outlets.clearSearch': 'शोध पुसा',
    'outlets.noneInFilter': 'या फिल्टरमध्ये एकही दुकान नाही',
    'outlets.showAll': 'सर्व दुकाने दाखवा',
    'outlets.notOnRoute': 'आजच्या रूटवर नाही',
    'persona.tag': 'डेमो · पर्सोना {no} · {label}',
    'persona.tip': 'डेमोसाठी: हे दुकान कोणत्या पर्सोनाचे आहे',

    'outlet.title': 'दुकानाची माहिती',
    'outlet.stop': 'आजचा रूट · थांबा {n}',
    'outlet.owner': 'मालक',
    'outlet.directions': 'रस्ता दाखवा',
    'outlet.directionsLabel': 'Google Maps मध्ये {name} पर्यंतचा रस्ता (नवीन टॅबमध्ये)',
    'outlet.savedToday': 'आज ऑर्डर सेव्ह झाली',
    'outlet.savedTodayN': 'आज {n} ऑर्डर सेव्ह झाल्या',
    'outlet.closed': '{range} बंद',
    'outlet.closedStarts': '{rel} सुरू',
    'outlet.closedNow': 'सध्या बंद',
    'outlet.book': 'ऑर्डर बुक करा',
    'outlet.bookAnother': 'आणखी एक ऑर्डर बुक करा',
    'outlet.continue': 'ऑर्डर पुढे सुरू ठेवा · {cases}',
    'outlet.notFound': 'दुकान सापडले नाही',
    'outlet.notFoundBody': 'डेटामध्ये “{id}” आयडीचे दुकान नाही.',
    'outlet.openList': 'दुकानांची यादी उघडा',
    'card.lastOrder': 'शेवटची ऑर्डर व भेट',
    'kv.lastOrder': 'शेवटची ऑर्डर',
    'kv.cases': 'पेट्या',
    'kv.value': 'मूल्य',
    'kv.lastVisit': 'शेवटची भेट',
    'kv.nextVisit': 'पुढची भेट',
    'kv.noOrders': 'अजून ऑर्डर नाही',
    'kv.noVisits': 'अजून भेट नाही',
    'kv.minutes': '{n} मिनिटे',
    'kv.plusFree': '+ {n} मोफत',
    'card.payment': 'पेमेंट',
    'kv.creditLimit': 'उधारी मर्यादा',
    'kv.outstanding': 'बाकी रक्कम',
    'kv.overdue': 'थकीत',
    'kv.overdueAmt': '{amt} थकीत',
    'kv.lastPayment': 'शेवटचे पेमेंट',
    'kv.noneYet': 'अजून नाही',
    'card.schemes': 'स्कीम',
    'scheme.applicable': 'लागू',
    'scheme.enrolled': 'सहभागी',
    'scheme.usedUp': '{cap} पैकी {used} वापरल्या',
    'scheme.usesTaken': '{month} मध्ये {cap} पैकी {used} वापर झाले',
    'scheme.none': 'आज एकही स्कीम सुरू नाही',
    'scheme.legend': 'सहभागी: लाभ आधीच मिळत आहे. लागू: ऑर्डरवर वापरता येईल. तपशीलासाठी स्कीमवर टॅप करा.',
    'card.history': 'ऑर्डर इतिहास',
    'history.last': { one: 'शेवटची ऑर्डर', other: 'शेवटच्या {n} ऑर्डर' },
    'history.since': '{date} पासून {orders}.',
    'history.empty': 'अजून ऑर्डर नाही',
    'history.emptyBody': 'या दुकानाने अजून आमच्याकडे ऑर्डर दिलेली नाही. पहिली ऑर्डर इथे दिसेल.',
    'history.strip': 'दरमहा पेट्या, {from} – {to}. {month} फक्त {date} पर्यंत.',
    'history.stripAria': 'दरमहा पेट्या.',
    'card.cooler': 'कूलर',
    'cooler.label': 'कूलर',
    'cooler.company': 'कंपनीचा कूलर · {count} × {litres} लि.',
    'cooler.lastAudit': 'शेवटची तपासणी',
    'cooler.onlyOurs': 'फक्त आमची पेये',
    'cooler.yes': 'हो',
    'cooler.otherBrands': 'नाही, इतर ब्रँड आत आहेत',
    'cooler.fillTemp': 'भराव · तापमान',
    'cooler.warm': '{t}°C (6°C पेक्षा जास्त)',
    'cooler.noAudit': 'अजून तपासणी नाही',
    'cooler.outage': 'दुपारी वीज जाते: कूलर गरम होतो.',
    'cooler.ownFridge': 'स्वतःचा फ्रिज',
    'cooler.iceBox': 'स्वतःचा आइस बॉक्स',
    'cooler.none': 'कूलर नाही · शेल्फवरून विक्री',
    'cooler.crates': 'रिकामे क्रेट',
    'card.bookings': 'येणारे कार्यक्रम',
    'bookings.next': '{date} पर्यंत {n} पैकी पुढचे 3 कार्यक्रम · एकूण ~{cases}.',
    'bookings.note': 'दुकानाच्या कॅलेंडरवरून रेपने नोंदवले. पेट्यांची संख्या अंदाजे आहे.',
    'card.notes': 'भेटीच्या नोंदी',
    'notes.empty': 'अजून नोंदी नाहीत',

    'sch.chip.free': '{buy} घ्या, {free} मोफत',
    'sch.chip.mix': ' · मिक्स',
    'sch.chip.pct': '{min}+ पेट्यांवर {pct}% सूट',
    'sch.chip.first': 'पहिल्या ऑर्डरवर {pct}% सूट',
    'sch.offer.freePooled': '{buy} पेट्या घ्या, {free} मोफत. {skus} यांचे कोणतेही मिश्रण चालेल.',
    'sch.offer.free': '{skus} च्या {buy} पेट्या घ्या, {free} मोफत.',
    'sch.offer.pct': '{skus} मिळून {min} किंवा जास्त पेट्या झाल्यास {pct}% सूट.',
    'sch.offer.first': 'पहिल्या {days} दिवसांतील दुकानांना संपूर्ण पहिल्या ऑर्डरवर {pct}% सूट.',
    'sch.reason.dates': 'स्कीमच्या तारखांबाहेर',
    'sch.reason.tier': '{tier} साठी नाही',
    'sch.reason.cooler': 'कंपनीचा कूलर हवा',
    'sch.reason.age': 'फक्त पहिल्या {days} दिवसांतील दुकानांसाठी',
    'sch.reason.first': 'फक्त पहिल्या ऑर्डरसाठी',

    'book.title': 'नवीन ऑर्डर',
    'book.search': 'उत्पादने शोधा',
    'book.category': 'प्रकार',
    'book.all': 'सर्व',
    'book.firstOrder': '{name}: या दुकानासाठी {offer}.',
    'book.review': 'तपासा',
    'book.cartEmpty': 'कार्ट रिकामी आहे',
    'book.noScheme': 'अजून स्कीम लागू नाही',
    'book.off': '{amt} सूट',
    'book.noMatch': '“{q}” शी जुळणारे उत्पादन नाही',
    'book.noMatchIn': '{cat} मध्ये नाही. ‘सर्व’ पहा.',
    'book.noMatchBody': 'चव, पॅक साइज किंवा कोड शोधा.',
    'book.noneIn': '{cat} मध्ये उत्पादने नाहीत',
    'book.rate': '{rate} / {unit}',
    'book.deposit': ' + अनामत',
    'book.mrp': 'MRP {mrp}',
    'book.returnable': 'परत करायच्या',
    'book.fewer': '{name}: एक {unit} कमी',
    'book.more': '{name}: एक {unit} जास्त',
    'book.qty': '{name}: {unit} संख्या',
    'book.hintWhole': 'फक्त पूर्ण पेट्या',
    'book.hintMax': 'जास्तीत जास्त {max} पेट्या',
    'book.capUsed': '{chip} · {month} मध्ये {cap} पैकी {cap} वापरल्या',
    'book.chipAdd': '{scheme} साठी {name} च्या {n} {unit} जोडा',
    'book.added': '{name} च्या {cases} जोडल्या · {scheme}',
    'book.openTitle': 'दुसरी ऑर्डर अजून उघडी आहे',
    'book.openBody': '{name} च्या {cases} अजून पाठवलेल्या नाहीत.',
    'book.choose': 'काय करायचे ते निवडा',
    'book.unsavedTitle': 'सेव्ह न केलेली ऑर्डर',
    'book.unsavedBody': '{name} ची ऑर्डर अजून पाठवलेली नाही: {cases} · {value}.',
    'book.unsavedQ': 'ती पुढे बदलायची, की रद्द करून {name} साठी नवीन ऑर्डर सुरू करायची?',
    'book.keep': '{name} ची ऑर्डर पुढे बदला',
    'book.discard': 'रद्द करा आणि इथे सुरू करा',

    'review.booked': 'ऑर्डरची किंमत',
    'review.estTitle': 'स्कीमचा अंदाज · आत्ता लागू नाही',
    'review.estFree': 'अपेक्षित मोफत पेट्या',
    'review.estOff': 'अंदाजे सूट',
    'review.estNote': 'स्कीमचा हिशेब नंतर डिस्ट्रिब्युटर करतो. दुकानदाराला ऑर्डरच्या किमतीचे बिल येते; लाभ क्लेममधून मिळतो.',
    'book.estFree': 'नंतर अंदाजे {free}',
    'book.estOff': 'नंतर अंदाजे {amt} सूट',
    'review.title': 'ऑर्डर सारांश',
    'review.delivery': 'डिलिव्हरी {date} · {rel}',
    'review.qtyRate': '{qty} × {rate}',
    'review.free': '+{n} मोफत · {name}',
    'review.edit': 'ऑर्डर बदला',
    'review.editShort': 'बदला',
    'review.schemes': 'या ऑर्डरवरील स्कीम',
    'review.totals': 'एकूण',
    'review.gross': 'एकूण रक्कम',
    'review.discounts': 'सूट',
    'review.net': 'निव्वळ',
    'review.totalCases': 'एकूण पेट्या',
    'review.paidFree': '({paid} विकत + {free} मोफत)',
    'review.submit': 'ऑर्डर पाठवा · {net}',
    'review.saving': 'सेव्ह होत आहे…',
    'review.toast': '{name} ची ऑर्डर सेव्ह झाली',
    'review.nothing': 'तपासण्यासारखे अजून काही नाही',
    'review.nothingBody': 'आधी {name} च्या ऑर्डरमध्ये उत्पादने जोडा.',
    'review.goBook': 'बुकिंगवर जा',
    'rn.off': '{name} · {reason}',
    'rn.free': '{name}: {sku} म्हणून +{free}',
    'rn.cap': ' · या महिन्यात {cap} पैकी {used} वापर',
    'rn.capReached': '. महिन्याची मर्यादा पूर्ण.',
    'rn.capFull': '{name}: या महिन्यात {cap} पैकी {used} वापर, मोफत पेटी नाही',
    'rn.pct': '{name}: {pct}% सूट · {amt}',
    'rn.pctFirst': '{name}: पहिल्या ऑर्डरवर {pct}% सूट · {amt}',

    'saved.title': 'ऑर्डर झाली',
    'saved.gone': 'ही ऑर्डर आता सेव्ह नाही',
    'saved.goneBody': 'डेमो रीसेट झाला असेल.',
    'saved.order': 'ऑर्डर',
    'saved.cases': 'पेट्या',
    'saved.lines': 'ओळी',
    'saved.discounts': 'सूट',
    'saved.net': 'निव्वळ',
    'saved.delivery': 'डिलिव्हरी',
    'saved.backRoute': 'रूटवर परत',
    'saved.list': 'दुकानांची यादी',
    'saved.view': '{name} पहा',

    'sd.title': 'स्कीम',
    'sd.notFound': 'स्कीम सापडली नाही',
    'sd.notFoundBody': '“{id}” आयडीची स्कीम नाही.',
    'sd.st.applicable': '{outlet} साठी लागू',
    'sd.st.enrolled': '{outlet} सहभागी आहे',
    'sd.st.used': '{outlet}: {month} चा वापर पूर्ण',
    'sd.st.not': '{outlet} साठी लागू नाही',
    'sd.st.applicableBody': 'पुढच्या ऑर्डरवर वापरता येईल.',
    'sd.st.enrolledBody': 'या दुकानाला हा लाभ आधीच मिळत आहे.',
    'sd.st.usedBody': 'या महिन्यातील सर्व {cap} मोफत पेट्या वापरल्या. {date} पासून पुन्हा लागू.',
    'sd.offer': 'ऑफर',
    'sd.details': 'तपशील',
    'sd.type': 'प्रकार',
    'sd.type.free-goods': 'मोफत पेट्या',
    'sd.type.percent-off': 'सूट',
    'sd.type.first-order': 'पहिल्या ऑर्डरवर सूट',
    'sd.type.program': 'मासिक योजना',
    'sd.valid': 'कालावधी',
    'sd.daysLeft': { one: '{n} दिवस बाकी', other: '{n} दिवस बाकी' },
    'sd.who': 'कोणाला मिळते',
    'sd.tiers': '{tiers} दुकाने',
    'sd.allOutlets': 'सर्व दुकाने',
    'sd.coolerOnly': 'कंपनीचा कूलर असलेली दुकाने',
    'sd.firstDays': 'पहिल्या {days} दिवसांतील दुकाने',
    'sd.limit': 'मासिक मर्यादा',
    'sd.limitVal': 'प्रत्येक दुकानाला {cap} मोफत पेट्या',
    'sd.used': '{month} मध्ये वापर',
    'sd.usedVal': '{cap} पैकी {used}',
    'sd.freeAs': 'मोफत पेटी कोणती',
    'sd.freeLargest': 'ऑर्डरमध्ये सर्वाधिक पेट्या असलेले उत्पादन',
    'sd.freeSame': 'तेच उत्पादन',
    'sd.paid': 'लाभ कसा मिळतो',
    'sd.pay.free-goods': 'मोफत पेटी डिलिव्हरीसोबत येते',
    'sd.pay.percent-off': 'बिलातून कमी होते',
    'sd.pay.first-order': 'बिलातून कमी होते',
    'sd.pay.program': 'दरमहा दिले जाते',
    'sd.also': 'तसेच',
    'sd.products': 'उत्पादने',
    'sd.perShop': 'दर महिना, प्रति दुकान',
    'sd.firstShort': 'नवीन दुकाने, पहिले {days} दिवस',
    'sd.coolerShort': 'कूलर असलेली',
    'sd.timesUsed': 'किती वेळा वापरले',
    'sd.freeGot': 'मिळालेल्या मोफत पेट्या',
    'sd.lastUsed': 'शेवटचा वापर',
    'sd.offerFree': '{buy} पेट्या घ्या, {free} मोफत पेटी मिळवा.',
    'sd.offerPct': '{min} किंवा जास्त पेट्या घ्या, {pct}% सूट मिळवा.',
    'sd.history': 'या दुकानातील वापर',
    'sd.historyEmpty': 'इथे अजून वापर नाही',
    'sd.historyApplied': 'लागू झाली',
    'sd.why': 'का नाही',
    'sd.audit': 'शेवटची कूलर तपासणी',
    'sd.book': 'या स्कीमसह ऑर्डर बुक करा',
    'sd.backOutlet': 'दुकानावर परत',

    'tp.title': 'बोलण्याचे मुद्दे',
    'tp.sub': 'या भेटीसाठी · पुढची भेट {date}',
    'tp.forYou': 'फक्त तुमच्यासाठी',
    'tp.forYouNote': 'मालकाला दाखवू नका',
    'tp.more': { one: 'आणखी 1 दाखवा', other: 'आणखी {n} दाखवा' },
    'tp.less': 'कमी दाखवा',
    'tp.open': 'बोलण्याचे मुद्दे · {n}',
    'tp.none': 'या भेटीत खास सांगण्यासारखे काही नाही.',
    'tp.f.ly': 'मागील वर्षी याच दिवसांत',
    'tp.f.recent': 'यंदा मागील {days} दिवसांत',
    'tp.f.topPacks': 'मागील वर्षीचे टॉप पॅक',
    'tp.f.till': 'पर्यंत लागू',
    'tp.f.firstTill': 'स्वागत ऑफर पर्यंत',
    'tp.f.freeLeft': 'या महिन्यात बाकी मोफत पेट्या',
    'tp.f.anyMix': 'यांचे कोणतेही मिश्रण चालेल',
    'tp.f.together': 'हे सर्व मिळून मोजले जातात',
    'tp.f.pack': 'पॅक',
    'tp.seeScheme': 'स्कीम पहा',
    'tp.cat.weather': 'हवामान',
    'tp.cat.history': 'गेल्या वर्षी',
    'tp.cat.event': 'येणारे',
    'tp.cat.bookings': 'कार्यक्रम',
    'tp.cat.scheme': 'स्कीम',
    'tp.cat.stock': 'स्टॉक',
    'tp.cat.cooler': 'कूलर',
    'tp.cat.payment': 'पेमेंट',
    'tp.cat.peers': 'जवळची दुकाने',
    'tp.cat.closure': 'सुट्टी',
    'tp.cat.empties': 'रिकामे क्रेट',
    'tp.src.forecast': '{date} चा अंदाज',
    'tp.src.orders': 'तुमच्या ऑर्डर',
    'tp.src.calendar': 'स्थानिक दिनदर्शिका',
    'tp.src.bookings': 'बुकिंग कॅलेंडर',
    'tp.src.stock': 'वितरकाचा स्टॉक, {date}',
    'tp.src.scheme': 'स्कीमच्या अटी',
    'tp.src.audit': 'कूलर तपासणी, {date}',
    'tp.src.peers': '{n} तशीच दुकाने',
    'tp.src.account': 'खाते',
    'tp.heat.title': '{date} पर्यंत कडक ऊन: {min}–{max}°C, पाऊस नाही',
    'tp.heat.titleShower': '{date} पर्यंत ऊन: {min}–{max}°C, तुरळक सरीची शक्यता',
    'tp.heat.chilled': 'या उन्हात थंड छोटे पॅक सर्वात जलद विकले जातात. पुण्यात पावसाळा साधारण {onset} च्या आसपास येतो.',
    'tp.heat.takehome': 'या उन्हात कुटुंबे मोठ्या बाटल्या आणि पाणी जास्त घेतात. पुण्यात पावसाळा साधारण {onset} च्या आसपास येतो.',
    'tp.ly.title': 'गेल्या वर्षी हेच {days} दिवस: {cases}',
    'tp.ly.body': 'यंदा मागील {days} दिवसांत: {recent}. तेव्हा {skus} सर्वात जास्त विकले.',
    'tp.ly.bodyNoRecent': 'तेव्हा {skus} सर्वात जास्त विकले.',
    'tp.closure.title': '{range} बंद',
    'tp.closure.soon': { one: 'उद्याच्या डिलिव्हरीपासून सुट्टीपर्यंत फक्त 1 विक्रीचा दिवस. साठा संपेल इतकीच ऑर्डर घ्या.', other: 'उद्याच्या डिलिव्हरीपासून सुट्टीपर्यंत फक्त {n} विक्रीचे दिवस. साठा संपेल इतकीच ऑर्डर घ्या.' },
    'tp.closure.now': 'सध्या बंद; {date} ला पुन्हा सुरू.',
    'tp.bookings.title': 'पुढच्या भेटीपूर्वी {functions}: ~{cases}',
    'tp.bookings.body': 'सर्वात मोठा: {date}, {event}.',
    'tp.event.up': 'इथे साधारण विक्री सुमारे {pct} वाढते.',
    'tp.event.down': 'इथे साधारण विक्री कमी होते.',
    'tp.event.packs': ' मुख्यतः {packs}.',
    'tp.scheme.left': 'या महिन्यात {cap} पैकी {left} मोफत पेट्या बाकी. {skus} यांचे कोणतेही मिश्रण चालेल.',
    'tp.scheme.leftSingle': 'या महिन्यात {cap} पैकी {left} मोफत पेट्या बाकी.',
    'tp.scheme.usedTitle': '{name}: {month} चा वापर पूर्ण',
    'tp.scheme.nextMonth': '{month} मधील सर्व {cap} मोफत पेट्या वापरल्या. पुढच्या भेटीतील ({date}) ऑर्डरवर पुन्हा मोफत पेट्या मिळतील.',
    'tp.scheme.pct': '{skus} मिळून मोजले जाते. {date} पर्यंत.',
    'tp.scheme.till': '{date} पर्यंत लागू.',
    'tp.scheme.first': 'नवीन दुकानांसाठी स्वागत ऑफर, {date} पर्यंत.',
    'tp.stock.rationed': '{sku}: एका ऑर्डरमध्ये जास्तीत जास्त {max} पेट्या',
    'tp.stock.out': '{sku} वितरकाकडे संपले आहे',
    'tp.stock.body': '{date} च्या स्टॉक अहवालानुसार; बदल झाला असू शकतो.',
    'tp.stock.alt': ' त्याऐवजी {alt} सुचवा.',
    'tp.peers.title': 'जवळची तशीच दुकाने आठवड्याला सुमारे {n} पेट्या विकतात',
    'tp.peers.body': 'मुख्यतः {skus}.',
    'tp.cooler.fixTitle': '{date} ला कूलर {fill}% भरलेला, {temp}°C',
    'tp.cooler.warm': '6°C पेक्षा गरम पेये हळू विकली जातात: कूलर चालू आणि बंद ठेवा.',
    'tp.cooler.fill': 'भरलेला कूलर जास्त विकतो: दुपारच्या गर्दीआधी भरून ठेवा.',
    'tp.cooler.outage': ' इथे दुपारी वीज जाते: सकाळीच भरा.',
    'tp.cooler.rewardTitle': 'कूलर बक्षीस: या महिन्यात {amt}',
    'tp.cooler.rewardBody': 'पुढच्या फोटो तपासणीपर्यंत आत फक्त आमची पेये ठेवा.',
    'tp.empties.title': '{n} रिकामे क्रेट तयार ठेवा',
    'tp.empties.body': 'काचेच्या बाटल्या रिकाम्या क्रेटच्या बदल्यातच मिळतात, क्रेटला क्रेट.',
    'tp.pay.overdue': '{amt} थकीत',
    'tp.pay.overdueBody': 'आज शिल्लक उधारी: {left}. शेवटचे पेमेंट {date}.',
    'tp.pay.cash': '{limit} पर्यंत उधारी; त्यावरील रक्कम रोख',
    'tp.pay.cashBody': 'मोठी ऑर्डर बुक करण्याआधी रोख आणि उधारी ठरवा.',

    'tier.Diamond': 'डायमंड',
    'tier.Gold': 'गोल्ड',
    'tier.Silver': 'सिल्व्हर',
    'tier.Bronze': 'ब्राँझ',
    'tier.Iron': 'आयर्न',
    'ch.Traditional Kirana': 'किराणा',
    'ch.Convenience': 'कन्व्हिनियन्स स्टोअर',
    'ch.Eating & Drinking': 'खाद्य व पेय',
    'ch.Education': 'शिक्षण',
    'ch.Entertainment & Leisure': 'मनोरंजन',
    'ch.Wholesale': 'घाऊक',
    'shop.Traditional Kirana': 'किराणा दुकान',
    'shop.Cold-drink shop': 'कोल्ड्रिंक दुकान',
    'shop.Banquet hall': 'मंगल कार्यालय',
    'shop.School canteen': 'शाळेचे कॅन्टीन',
    'shop.Snack stall': 'नाश्त्याचा स्टॉल',
    'shop.Beverage wholesaler': 'पेयांचे घाऊक विक्रेते',
    'cat.Sparkling': 'कोल्ड्रिंक',
    'cat.Juice drinks': 'ज्यूस',
    'cat.Water': 'पाणी',
    'cat.Energy': 'एनर्जी ड्रिंक',
    'area.Kothrud': 'कोथरूड',
    'area.Warje': 'वारजे',
    'area.Bavdhan': 'बावधन',
    'area.Pashan': 'पाषाण',
    'region.Pune West': 'पुणे पश्चिम',
    'repRole.Pre-seller': 'प्री-सेलर',
    'role.Manager': 'व्यवस्थापक',
    'role.Canteen contractor': 'कॅन्टीन कंत्राटदार',
    'schOffer.PRG-PURITY': 'मासिक फोटो तपासणीत कूलरमध्ये फक्त आमची पेये असल्यास दरमहा {amt}.',
    'schExtras.SCH-SS26': 'पहिल्या पात्र ऑर्डरसोबत मोफत कूलर शेल्फ-स्ट्रिप',
    'schExtras.PRG-PURITY': 'नवीन कूलर फक्त डायमंड, गोल्ड आणि सिल्व्हर दुकानांना मिळतात',
  },

  hi: {
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.cancel': 'रद्द करें',
    'common.clear': 'हटाएँ',
    'common.language': 'भाषा',
    'common.chooseLanguage': 'भाषा चुनें',
    'common.today': 'आज',
    'common.yesterday': '1 दिन पहले',
    'common.tomorrow': 'कल',
    'common.daysAgo': '{n} दिन पहले',
    'common.inDays': '{n} दिन में',
    'common.ongoing': 'लगातार जारी',
    'common.till': '{date} तक',
    'common.and': 'और',

    'unit.case': 'पेटी',
    'unit.crate': 'क्रेट',
    'n.case': '{n} पेटी',
    'n.crate': '{n} क्रेट',
    'n.freeCase': '{n} फ़्री पेटी',
    'n.outlet': { one: '{n} दुकान', other: '{n} दुकानें' },
    'n.order': '{n} ऑर्डर',
    'n.line': '{n} लाइन',
    'n.visitsMonth': 'महीने में {n} विज़िट',
    'n.visitsShort': '{n}×/महीना',
    'n.function': '{n} कार्यक्रम',
    'pack.PET': 'बोतल',
    'pack.glass': 'बोतल',
    'pack.can': 'कैन',
    'pack.tetra': 'पैक',
    'pack.units': 'नग',

    'demo.tag': 'डेमो',
    'demo.reset': 'डेमो रीसेट',
    'demo.stub': 'स्टब',
    'demo.resetTitle': 'डेमो रीसेट करें?',
    'demo.resetBody': 'इस डेमो में सेव किए गए {orders} हट जाएँगे और आप साइन आउट हो जाएँगे।',
    'demo.resetBodyNone': 'अभी कोई ऑर्डर सेव नहीं है। आप साइन आउट होंगे और डेमो फिर से शुरू होगा।',
    'demo.resetNote': 'डेटा फ़ाइलों के पुराने ऑर्डर वैसे ही रहेंगे।',
    'demo.resetDone': 'डेमो रीसेट हो गया। सेव किए गए ऑर्डर हटा दिए गए।',
    'fatal.served': 'डेमो डेटा लोड नहीं हुआ',
    'fatal.local': 'इस पेज में डेटा नहीं है',
    'fatal.servedHelp': 'जाँचें कि data/ फ़ोल्डर इस पेज के साथ है, डेटा अनुबंध की सभी फ़ाइलें मौजूद हैं और हर फ़ाइल सही JSON है।',
    'fatal.localHelp': 'gt-app.html खोलें (एक-फ़ाइल वाला संस्करण, जिसमें डेटा अंदर ही है), या होस्ट किया गया लिंक खोलें।',

    'login.eyebrow': 'फ़ील्ड सेल्स · {region}',
    'login.proto': 'प्रोटोटाइप',
    'login.lede': '{distributor} के लिए आज का रूट खोलने के लिए साइन इन करें।',
    'login.username': 'यूज़रनेम',
    'login.usernamePh': 'आपका नाम',
    'login.password': 'पासवर्ड',
    'login.errUser': 'यूज़रनेम लिखें',
    'login.errPass': 'पासवर्ड लिखें',
    'login.submit': 'साइन इन करें',
    'login.hint': 'कोई भी यूज़रनेम और पासवर्ड चलेगा। आपका यूज़रनेम सेल्स रेप के नाम के रूप में दिखेगा।',
    'login.demoDate': 'डेमो तारीख़',

    'home.title': 'आज',
    'home.allOutlets': 'सभी दुकानें',
    'home.hi': 'नमस्ते, {name}',
    'home.today': 'आज {outlets}',
    'home.visited': 'विज़िट पूरी: {n}',
    'home.routeDone': 'रूट पूरा',
    'home.progress': 'विज़िट की गई दुकानें',
    'home.orders': 'ऑर्डर',
    'home.cases': 'पेटी',
    'home.value': 'मूल्य',
    'home.shownOf': 'आज के रूट की {total} में से {shown} दुकानें प्रोटोटाइप में दिखाई गई हैं।',
    'home.route': 'आज का रूट · {region}',
    'home.noRoute': 'आज के रूट पर कोई दुकान नहीं',
    'home.noRouteBody': 'कोई भी दुकान खोजने के लिए दुकानों की सूची खोलें।',
    'home.seeAll': 'सभी दुकानें देखें',
    'status.toVisit': 'विज़िट बाकी',
    'status.saved': 'ऑर्डर सेव · {cases} · {value}',
    'status.savedN': '{n} ऑर्डर सेव · {cases} · {value}',
    'status.inProgress': 'ऑर्डर जारी · {cases}',
    'status.savedShort': 'ऑर्डर सेव',
    'status.savedShortN': '{n} ऑर्डर सेव',

    'outlets.title': 'सभी दुकानें',
    'outlets.search': 'नाम, इलाका या प्रकार खोजें',
    'outlets.searchLabel': 'दुकानें खोजें',
    'outlets.filters': 'दुकानें फ़िल्टर करें',
    'outlets.all': 'सभी',
    'outlets.route': 'आज का रूट',
    'outlets.count': '{total} में से {shown}',
    'outlets.noMatch': '“{q}” से मेल खाती कोई दुकान नहीं',
    'outlets.noMatchAll': 'स्पेलिंग जाँचें, या इलाके/प्रकार से खोजें।',
    'outlets.noMatchFilter': 'दूसरा फ़िल्टर चुनें, या खोज हटाएँ।',
    'outlets.clearSearch': 'खोज हटाएँ',
    'outlets.noneInFilter': 'इस फ़िल्टर में कोई दुकान नहीं',
    'outlets.showAll': 'सभी दुकानें दिखाएँ',
    'outlets.notOnRoute': 'आज के रूट पर नहीं',
    'persona.tag': 'डेमो · पर्सोना {no} · {label}',
    'persona.tip': 'डेमो के लिए: यह दुकान किस पर्सोना की है',

    'outlet.title': 'दुकान की जानकारी',
    'outlet.stop': 'आज का रूट · स्टॉप {n}',
    'outlet.owner': 'मालिक',
    'outlet.directions': 'रास्ता देखें',
    'outlet.directionsLabel': 'Google Maps में {name} तक का रास्ता (नए टैब में)',
    'outlet.savedToday': 'आज ऑर्डर सेव हुआ',
    'outlet.savedTodayN': 'आज {n} ऑर्डर सेव हुए',
    'outlet.closed': '{range} बंद',
    'outlet.closedStarts': '{rel} शुरू',
    'outlet.closedNow': 'अभी बंद',
    'outlet.book': 'ऑर्डर बुक करें',
    'outlet.bookAnother': 'एक और ऑर्डर बुक करें',
    'outlet.continue': 'ऑर्डर जारी रखें · {cases}',
    'outlet.notFound': 'दुकान नहीं मिली',
    'outlet.notFoundBody': 'डेटा में “{id}” आईडी वाली कोई दुकान नहीं है।',
    'outlet.openList': 'दुकानों की सूची खोलें',
    'card.lastOrder': 'आख़िरी ऑर्डर और विज़िट',
    'kv.lastOrder': 'आख़िरी ऑर्डर',
    'kv.cases': 'पेटी',
    'kv.value': 'मूल्य',
    'kv.lastVisit': 'आख़िरी विज़िट',
    'kv.nextVisit': 'अगली विज़िट',
    'kv.noOrders': 'अभी कोई ऑर्डर नहीं',
    'kv.noVisits': 'अभी कोई विज़िट नहीं',
    'kv.minutes': '{n} मिनट',
    'kv.plusFree': '+ {n} फ़्री',
    'card.payment': 'भुगतान',
    'kv.creditLimit': 'उधार सीमा',
    'kv.outstanding': 'बकाया',
    'kv.overdue': 'ओवरड्यू',
    'kv.overdueAmt': '{amt} ओवरड्यू',
    'kv.lastPayment': 'आख़िरी भुगतान',
    'kv.noneYet': 'अभी नहीं',
    'card.schemes': 'स्कीम',
    'scheme.applicable': 'लागू',
    'scheme.enrolled': 'शामिल',
    'scheme.usedUp': '{cap} में से {used} इस्तेमाल',
    'scheme.usesTaken': '{month} में {cap} में से {used} बार इस्तेमाल',
    'scheme.none': 'आज कोई स्कीम नहीं चल रही',
    'scheme.legend': 'शामिल: लाभ पहले से मिल रहा है। लागू: ऑर्डर पर इस्तेमाल हो सकती है। विवरण के लिए स्कीम पर टैप करें।',
    'card.history': 'ऑर्डर इतिहास',
    'history.last': { one: 'आख़िरी ऑर्डर', other: 'आख़िरी {n} ऑर्डर' },
    'history.since': '{date} से {orders}।',
    'history.empty': 'अभी कोई ऑर्डर नहीं',
    'history.emptyBody': 'इस दुकान ने अभी तक हमसे ऑर्डर नहीं दिया है। पहला ऑर्डर यहाँ दिखेगा।',
    'history.strip': 'हर महीने की पेटी, {from} – {to}। {month} सिर्फ़ {date} तक।',
    'history.stripAria': 'हर महीने की पेटी।',
    'card.cooler': 'कूलर',
    'cooler.label': 'कूलर',
    'cooler.company': 'कंपनी का कूलर · {count} × {litres} ली.',
    'cooler.lastAudit': 'आख़िरी ऑडिट',
    'cooler.onlyOurs': 'सिर्फ़ हमारे ड्रिंक',
    'cooler.yes': 'हाँ',
    'cooler.otherBrands': 'नहीं, दूसरे ब्रांड भी अंदर हैं',
    'cooler.fillTemp': 'भराव · तापमान',
    'cooler.warm': '{t}°C (6°C से ज़्यादा)',
    'cooler.noAudit': 'अभी ऑडिट नहीं',
    'cooler.outage': 'दोपहर में बिजली कटती है: कूलर गरम हो जाता है।',
    'cooler.ownFridge': 'अपना फ़्रिज',
    'cooler.iceBox': 'अपना आइस बॉक्स',
    'cooler.none': 'कूलर नहीं · शेल्फ़ से बिक्री',
    'cooler.crates': 'ख़ाली क्रेट',
    'card.bookings': 'आने वाले कार्यक्रम',
    'bookings.next': '{date} तक {n} में से अगले 3 कार्यक्रम · कुल ~{cases}।',
    'bookings.note': 'दुकान के कैलेंडर से रेप ने दर्ज किए। पेटी की संख्या अनुमानित है।',
    'card.notes': 'विज़िट नोट्स',
    'notes.empty': 'अभी कोई नोट नहीं',

    'sch.chip.free': '{buy} लें, {free} फ़्री',
    'sch.chip.mix': ' · मिक्स',
    'sch.chip.pct': '{min}+ पेटी पर {pct}% छूट',
    'sch.chip.first': 'पहले ऑर्डर पर {pct}% छूट',
    'sch.offer.freePooled': '{buy} पेटी लें, {free} फ़्री। {skus} में से कोई भी मिलाकर चलेगा।',
    'sch.offer.free': '{skus} की {buy} पेटी लें, {free} फ़्री।',
    'sch.offer.pct': '{skus} मिलाकर {min} या ज़्यादा पेटी होने पर {pct}% छूट।',
    'sch.offer.first': 'पहले {days} दिन वाली दुकानों को पूरे पहले ऑर्डर पर {pct}% छूट।',
    'sch.reason.dates': 'स्कीम की तारीख़ों से बाहर',
    'sch.reason.tier': '{tier} के लिए नहीं',
    'sch.reason.cooler': 'कंपनी का कूलर ज़रूरी',
    'sch.reason.age': 'सिर्फ़ पहले {days} दिन वाली दुकानों के लिए',
    'sch.reason.first': 'सिर्फ़ पहले ऑर्डर पर',

    'book.title': 'नया ऑर्डर',
    'book.search': 'प्रोडक्ट खोजें',
    'book.category': 'प्रकार',
    'book.all': 'सभी',
    'book.firstOrder': '{name}: इस दुकान के लिए {offer}।',
    'book.review': 'जाँचें',
    'book.cartEmpty': 'कार्ट ख़ाली है',
    'book.noScheme': 'अभी कोई स्कीम लागू नहीं',
    'book.off': '{amt} छूट',
    'book.noMatch': '“{q}” से मेल खाता कोई प्रोडक्ट नहीं',
    'book.noMatchIn': '{cat} में नहीं। ‘सभी’ देखें।',
    'book.noMatchBody': 'फ़्लेवर, पैक साइज़ या कोड खोजें।',
    'book.noneIn': '{cat} में कोई प्रोडक्ट नहीं',
    'book.rate': '{rate} / {unit}',
    'book.deposit': ' + जमा राशि',
    'book.mrp': 'MRP {mrp}',
    'book.returnable': 'वापसी वाली',
    'book.fewer': '{name}: एक {unit} कम',
    'book.more': '{name}: एक {unit} ज़्यादा',
    'book.qty': '{name}: {unit} की संख्या',
    'book.hintWhole': 'सिर्फ़ पूरी पेटी',
    'book.hintMax': 'ज़्यादा से ज़्यादा {max} पेटी',
    'book.capUsed': '{chip} · {month} में {cap} में से {cap} इस्तेमाल',
    'book.chipAdd': '{scheme} के लिए {name} की {n} {unit} जोड़ें',
    'book.added': '{name} की {cases} जोड़ी गईं · {scheme}',
    'book.openTitle': 'दूसरा ऑर्डर अभी खुला है',
    'book.openBody': '{name} की {cases} अभी भेजी नहीं गई हैं।',
    'book.choose': 'क्या करना है, चुनें',
    'book.unsavedTitle': 'बिना सेव किया ऑर्डर',
    'book.unsavedBody': '{name} का ऑर्डर अभी भेजा नहीं गया: {cases} · {value}।',
    'book.unsavedQ': 'उसे आगे बदलें, या हटाकर {name} के लिए नया ऑर्डर शुरू करें?',
    'book.keep': '{name} का ऑर्डर बदलते रहें',
    'book.discard': 'हटाएँ और यहाँ शुरू करें',

    'review.booked': 'ऑर्डर की कीमत',
    'review.estTitle': 'स्कीम का अंदाज़ा · अभी लागू नहीं',
    'review.estFree': 'अपेक्षित फ़्री पेटी',
    'review.estOff': 'अनुमानित छूट',
    'review.estNote': 'स्कीम का हिसाब बाद में डिस्ट्रीब्यूटर करता है। दुकानदार को ऑर्डर की कीमत का बिल आता है; फ़ायदा क्लेम से मिलता है।',
    'book.estFree': 'बाद में लगभग {free}',
    'book.estOff': 'बाद में लगभग {amt} छूट',
    'review.title': 'ऑर्डर सारांश',
    'review.delivery': 'डिलीवरी {date} · {rel}',
    'review.qtyRate': '{qty} × {rate}',
    'review.free': '+{n} फ़्री · {name}',
    'review.edit': 'ऑर्डर बदलें',
    'review.editShort': 'बदलें',
    'review.schemes': 'इस ऑर्डर पर स्कीम',
    'review.totals': 'कुल',
    'review.gross': 'कुल रक़म',
    'review.discounts': 'छूट',
    'review.net': 'नेट',
    'review.totalCases': 'कुल पेटी',
    'review.paidFree': '({paid} पेड + {free} फ़्री)',
    'review.submit': 'ऑर्डर भेजें · {net}',
    'review.saving': 'सेव हो रहा है…',
    'review.toast': '{name} का ऑर्डर सेव हो गया',
    'review.nothing': 'जाँचने के लिए अभी कुछ नहीं',
    'review.nothingBody': 'पहले {name} के ऑर्डर में प्रोडक्ट जोड़ें।',
    'review.goBook': 'बुकिंग पर जाएँ',
    'rn.off': '{name} · {reason}',
    'rn.free': '{name}: {sku} के रूप में +{free}',
    'rn.cap': ' · इस महीने {cap} में से {used} बार',
    'rn.capReached': '। महीने की सीमा पूरी।',
    'rn.capFull': '{name}: इस महीने {cap} में से {used} बार, फ़्री पेटी नहीं',
    'rn.pct': '{name}: {pct}% छूट · {amt}',
    'rn.pctFirst': '{name}: पहले ऑर्डर पर {pct}% छूट · {amt}',

    'saved.title': 'ऑर्डर हो गया',
    'saved.gone': 'यह ऑर्डर अब सेव नहीं है',
    'saved.goneBody': 'शायद डेमो रीसेट हो गया है।',
    'saved.order': 'ऑर्डर',
    'saved.cases': 'पेटी',
    'saved.lines': 'लाइनें',
    'saved.discounts': 'छूट',
    'saved.net': 'नेट',
    'saved.delivery': 'डिलीवरी',
    'saved.backRoute': 'रूट पर वापस',
    'saved.list': 'दुकानों की सूची',
    'saved.view': '{name} देखें',

    'sd.title': 'स्कीम',
    'sd.notFound': 'स्कीम नहीं मिली',
    'sd.notFoundBody': '“{id}” आईडी वाली कोई स्कीम नहीं है।',
    'sd.st.applicable': '{outlet} पर लागू',
    'sd.st.enrolled': '{outlet} शामिल है',
    'sd.st.used': '{outlet}: {month} का इस्तेमाल पूरा',
    'sd.st.not': '{outlet} पर लागू नहीं',
    'sd.st.applicableBody': 'अगले ऑर्डर पर इस्तेमाल हो सकती है।',
    'sd.st.enrolledBody': 'इस दुकान को यह लाभ पहले से मिल रहा है।',
    'sd.st.usedBody': 'इस महीने की सभी {cap} फ़्री पेटी इस्तेमाल हो चुकी हैं। {date} से फिर लागू।',
    'sd.offer': 'ऑफ़र',
    'sd.details': 'विवरण',
    'sd.type': 'प्रकार',
    'sd.type.free-goods': 'फ़्री पेटी',
    'sd.type.percent-off': 'छूट',
    'sd.type.first-order': 'पहले ऑर्डर पर छूट',
    'sd.type.program': 'मासिक प्रोग्राम',
    'sd.valid': 'अवधि',
    'sd.daysLeft': '{n} दिन बाकी',
    'sd.who': 'किसे मिलेगी',
    'sd.tiers': '{tiers} दुकानें',
    'sd.allOutlets': 'सभी दुकानें',
    'sd.coolerOnly': 'कंपनी कूलर वाली दुकानें',
    'sd.firstDays': 'पहले {days} दिन वाली दुकानें',
    'sd.limit': 'मासिक सीमा',
    'sd.limitVal': 'हर दुकान को {cap} फ़्री पेटी',
    'sd.used': '{month} में इस्तेमाल',
    'sd.usedVal': '{cap} में से {used}',
    'sd.freeAs': 'फ़्री पेटी कौन-सी',
    'sd.freeLargest': 'ऑर्डर में सबसे ज़्यादा पेटी वाला प्रोडक्ट',
    'sd.freeSame': 'वही प्रोडक्ट',
    'sd.paid': 'लाभ कैसे मिलता है',
    'sd.pay.free-goods': 'फ़्री पेटी डिलीवरी के साथ आती है',
    'sd.pay.percent-off': 'बिल में से कम होती है',
    'sd.pay.first-order': 'बिल में से कम होती है',
    'sd.pay.program': 'हर महीने मिलता है',
    'sd.also': 'साथ में',
    'sd.products': 'प्रोडक्ट',
    'sd.perShop': 'हर महीने, प्रति दुकान',
    'sd.firstShort': 'नई दुकानें, पहले {days} दिन',
    'sd.coolerShort': 'कूलर वाली',
    'sd.timesUsed': 'कितनी बार इस्तेमाल',
    'sd.freeGot': 'मिली मुफ़्त पेटियाँ',
    'sd.lastUsed': 'आख़िरी इस्तेमाल',
    'sd.offerFree': '{buy} पेटी लें, {free} फ़्री पेटी पाएँ।',
    'sd.offerPct': '{min} या ज़्यादा पेटी लें, {pct}% छूट पाएँ।',
    'sd.history': 'इस दुकान पर इस्तेमाल',
    'sd.historyEmpty': 'यहाँ अभी इस्तेमाल नहीं हुई',
    'sd.historyApplied': 'लागू हुई',
    'sd.why': 'क्यों नहीं',
    'sd.audit': 'आख़िरी कूलर ऑडिट',
    'sd.book': 'इस स्कीम के साथ ऑर्डर बुक करें',
    'sd.backOutlet': 'दुकान पर वापस',

    'tp.title': 'बात करने के मुद्दे',
    'tp.sub': 'इस विज़िट के लिए · अगली विज़िट {date}',
    'tp.forYou': 'सिर्फ़ आपके लिए',
    'tp.forYouNote': 'मालिक को न दिखाएँ',
    'tp.more': '{n} और दिखाएँ',
    'tp.less': 'कम दिखाएँ',
    'tp.open': 'बात करने के मुद्दे · {n}',
    'tp.none': 'इस विज़िट में ख़ास बताने को कुछ नहीं।',
    'tp.f.ly': 'पिछले साल इन्हीं दिनों',
    'tp.f.recent': 'इस साल पिछले {days} दिन',
    'tp.f.topPacks': 'पिछले साल के टॉप पैक',
    'tp.f.till': 'तक लागू',
    'tp.f.firstTill': 'स्वागत ऑफ़र तक',
    'tp.f.freeLeft': 'इस महीने बची फ़्री पेटी',
    'tp.f.anyMix': 'इनमें से कोई भी मिलाकर चलेगा',
    'tp.f.together': 'ये सब मिलाकर गिने जाते हैं',
    'tp.f.pack': 'पैक',
    'tp.seeScheme': 'स्कीम देखें',
    'tp.cat.weather': 'मौसम',
    'tp.cat.history': 'पिछले साल',
    'tp.cat.event': 'आने वाला',
    'tp.cat.bookings': 'कार्यक्रम',
    'tp.cat.scheme': 'स्कीम',
    'tp.cat.stock': 'स्टॉक',
    'tp.cat.cooler': 'कूलर',
    'tp.cat.payment': 'भुगतान',
    'tp.cat.peers': 'आस-पास की दुकानें',
    'tp.cat.closure': 'छुट्टी',
    'tp.cat.empties': 'ख़ाली क्रेट',
    'tp.src.forecast': '{date} का पूर्वानुमान',
    'tp.src.orders': 'आपके ऑर्डर',
    'tp.src.calendar': 'स्थानीय कैलेंडर',
    'tp.src.bookings': 'बुकिंग कैलेंडर',
    'tp.src.stock': 'डिस्ट्रीब्यूटर स्टॉक, {date}',
    'tp.src.scheme': 'स्कीम की शर्तें',
    'tp.src.audit': 'कूलर ऑडिट, {date}',
    'tp.src.peers': '{n} ऐसी ही दुकानें',
    'tp.src.account': 'खाता',
    'tp.heat.title': '{date} तक तेज़ गर्मी: {min}–{max}°C, बारिश नहीं',
    'tp.heat.titleShower': '{date} तक गर्मी: {min}–{max}°C, छिटपुट बौछार संभव',
    'tp.heat.chilled': 'इस गर्मी में ठंडे छोटे पैक सबसे तेज़ बिकते हैं। पुणे में मानसून आम तौर पर {onset} के आसपास आता है।',
    'tp.heat.takehome': 'इस गर्मी में परिवार बड़ी बोतलें और पानी ज़्यादा लेते हैं। पुणे में मानसून आम तौर पर {onset} के आसपास आता है।',
    'tp.ly.title': 'पिछले साल यही {days} दिन: {cases}',
    'tp.ly.body': 'इस साल पिछले {days} दिन: {recent}। तब {skus} सबसे ज़्यादा बिके।',
    'tp.ly.bodyNoRecent': 'तब {skus} सबसे ज़्यादा बिके।',
    'tp.closure.title': '{range} बंद',
    'tp.closure.soon': 'कल की डिलीवरी से छुट्टी तक सिर्फ़ {n} बिक्री के दिन। स्टॉक ख़त्म हो, बस इतना ही ऑर्डर लें।',
    'tp.closure.now': 'अभी बंद; {date} को फिर खुलेगा।',
    'tp.bookings.title': 'अगली विज़िट से पहले {functions}: ~{cases}',
    'tp.bookings.body': 'सबसे बड़ा: {date}, {event}।',
    'tp.event.up': 'यहाँ आम तौर पर बिक्री लगभग {pct} बढ़ती है।',
    'tp.event.down': 'यहाँ आम तौर पर बिक्री घटती है।',
    'tp.event.packs': ' ज़्यादातर {packs}।',
    'tp.scheme.left': 'इस महीने {cap} में से {left} फ़्री पेटी बाकी। {skus} में से कोई भी मिलाकर चलेगा।',
    'tp.scheme.leftSingle': 'इस महीने {cap} में से {left} फ़्री पेटी बाकी।',
    'tp.scheme.usedTitle': '{name}: {month} का इस्तेमाल पूरा',
    'tp.scheme.nextMonth': '{month} की सभी {cap} फ़्री पेटी इस्तेमाल हो चुकी हैं। अगली विज़िट ({date}) के ऑर्डर पर फिर फ़्री पेटी मिलेंगी।',
    'tp.scheme.pct': '{skus} मिलाकर गिने जाते हैं। {date} तक।',
    'tp.scheme.till': '{date} तक लागू।',
    'tp.scheme.first': 'नई दुकानों के लिए स्वागत ऑफ़र, {date} तक।',
    'tp.stock.rationed': '{sku}: एक ऑर्डर में ज़्यादा से ज़्यादा {max} पेटी',
    'tp.stock.out': '{sku} डिस्ट्रीब्यूटर के पास ख़त्म है',
    'tp.stock.body': '{date} की स्टॉक रिपोर्ट के अनुसार; बदल सकती है।',
    'tp.stock.alt': ' इसकी जगह {alt} दें।',
    'tp.peers.title': 'आस-पास की ऐसी दुकानें हफ़्ते में लगभग {n} पेटी बेचती हैं',
    'tp.peers.body': 'ज़्यादातर {skus}।',
    'tp.cooler.fixTitle': '{date} को कूलर {fill}% भरा था, {temp}°C',
    'tp.cooler.warm': '6°C से गरम ड्रिंक धीरे बिकते हैं: कूलर चालू और बंद रखें।',
    'tp.cooler.fill': 'भरा कूलर ज़्यादा बेचता है: दोपहर की भीड़ से पहले भर दें।',
    'tp.cooler.outage': ' यहाँ दोपहर में बिजली कटती है: सुबह ही भर दें।',
    'tp.cooler.rewardTitle': 'कूलर इनाम: इस महीने {amt}',
    'tp.cooler.rewardBody': 'अगले फ़ोटो ऑडिट तक अंदर सिर्फ़ हमारे ड्रिंक रखें।',
    'tp.empties.title': '{n} ख़ाली क्रेट तैयार रखें',
    'tp.empties.body': 'काँच की बोतलें ख़ाली क्रेट के बदले ही मिलती हैं, क्रेट के बदले क्रेट।',
    'tp.pay.overdue': '{amt} ओवरड्यू',
    'tp.pay.overdueBody': 'आज बची उधार सीमा: {left}। आख़िरी भुगतान {date}।',
    'tp.pay.cash': '{limit} तक उधार; उससे ऊपर नकद',
    'tp.pay.cashBody': 'बड़ा ऑर्डर बुक करने से पहले नकद और उधार तय करें।',

    'tier.Diamond': 'डायमंड',
    'tier.Gold': 'गोल्ड',
    'tier.Silver': 'सिल्वर',
    'tier.Bronze': 'ब्रॉन्ज़',
    'tier.Iron': 'आयरन',
    'ch.Traditional Kirana': 'किराना',
    'ch.Convenience': 'कन्वीनियंस स्टोर',
    'ch.Eating & Drinking': 'खान-पान',
    'ch.Education': 'शिक्षा',
    'ch.Entertainment & Leisure': 'मनोरंजन',
    'ch.Wholesale': 'थोक',
    'shop.Traditional Kirana': 'किराना दुकान',
    'shop.Cold-drink shop': 'कोल्ड ड्रिंक की दुकान',
    'shop.Banquet hall': 'बैंक्वेट हॉल',
    'shop.School canteen': 'स्कूल कैंटीन',
    'shop.Snack stall': 'नाश्ते का स्टॉल',
    'shop.Beverage wholesaler': 'ड्रिंक थोक विक्रेता',
    'cat.Sparkling': 'कोल्ड ड्रिंक',
    'cat.Juice drinks': 'जूस',
    'cat.Water': 'पानी',
    'cat.Energy': 'एनर्जी ड्रिंक',
    'area.Kothrud': 'कोथरूड',
    'area.Warje': 'वारजे',
    'area.Bavdhan': 'बावधन',
    'area.Pashan': 'पाषाण',
    'region.Pune West': 'पुणे पश्चिम',
    'repRole.Pre-seller': 'प्री-सेलर',
    'role.Manager': 'मैनेजर',
    'role.Canteen contractor': 'कैंटीन ठेकेदार',
    'schOffer.PRG-PURITY': 'मासिक फ़ोटो ऑडिट में कूलर में सिर्फ़ हमारे ड्रिंक हों तो हर महीने {amt}।',
    'schExtras.SCH-SS26': 'पहले योग्य ऑर्डर के साथ फ़्री कूलर शेल्फ़-स्ट्रिप',
    'schExtras.PRG-PURITY': 'नए कूलर सिर्फ़ डायमंड, गोल्ड और सिल्वर दुकानों को मिलते हैं',
  },
};

Object.assign(STRINGS.en, FIELD_EN);
Object.assign(STRINGS.mr, FIELD_MR);
Object.assign(STRINGS.hi, FIELD_HI);
