// Hindi text for the field features (keys start with "f."), same keys as strings-en.js.
// Merged into STRINGS.hi by js/strings.js. Simple spoken Hindi; pack names stay as they are.

export const FIELD_HI = {
  'f.common.ok': 'ठीक है',

  // Login
  'f.login.title': 'आज के रूट के लिए तैयार?',
  'f.login.show': 'दिखाएँ',
  'f.login.hide': 'छुपाएँ',
  'f.login.demo': 'डेमो: कोई भी नाम और पासवर्ड चलेगा।',

  // Landing: header
  'f.clock.in': 'दिन शुरू करें',
  'f.clock.out': 'खत्म',
  'f.clock.onFor': 'ड्यूटी पर · {dur}',
  'f.clock.dayDone': 'दिन पूरा · {dur}',
  'f.clock.hm': '{h}घं {m}मि',
  'f.clock.m': '{m} मि',
  'f.clock.inToast': 'दिन {time} पर शुरू हुआ',
  'f.clock.outToast': 'दिन खत्म · {dur} ड्यूटी',
  'f.rank.chip': '{total} में {rank}वाँ',
  'f.target.title': 'प्री-समर टारगेट',
  'f.target.cases': 'पेटी',
  'f.target.today': 'आज',
  'f.target.daysLeft': { one: '1 दिन बाकी', other: '{n} दिन बाकी' },
  'f.target.pace': 'पूरा करने के लिए रोज़ लगभग {n} पेटी बेचें',
  'f.target.done': 'टारगेट पूरा! हर अतिरिक्त पेटी आपकी बढ़त बढ़ाती है।',
  'f.target.counts': 'समर SKU: {skus}',
  'f.target.window': '{from} से {to}',
  'f.target.month': 'अप्रैल टारगेट',

  // Landing: alerts and the updates screen
  'f.alert.head': { one: 'आज का 1 अपडेट', other: 'आज के {n} अपडेट' },
  'f.alert.viewAll': 'अपडेट देखें',
  'f.alert.none': 'कोई नया अपडेट नहीं',
  'f.alert.tagOut': 'स्टॉक खत्म',
  'f.alert.tagLow': 'स्टॉक कम',
  'f.upd.title': 'अपडेट',
  'f.upd.unread': { one: '1 अभी खोला नहीं', other: '{n} अभी खोले नहीं' },
  'f.upd.stock': 'डिस्ट्रीब्यूटर स्टॉक',
  'f.upd.schemes': 'स्कीम',
  'f.alert.view': 'देखें',
  'f.alert.tagNew': 'नई स्कीम',
  'f.alert.tagSoon': 'स्कीम जल्द',
  'f.alert.tagUp': 'स्टॉक वापस आया',
  'f.alert.tagDown': 'स्टॉक अलर्ट',
  'f.alert.from': '{date} से',
  'f.alert.till': '{date} तक',
  'f.alert.rationUp': '{name}: सीमा बढ़कर प्रति दुकान {n}',
  'f.alert.rationDown': '{name}: सीमा घटकर प्रति दुकान {n}',
  'f.alert.stock.out-of-stock': '{name} स्टॉक में नहीं',
  'f.alert.stock.rationed': '{name}: प्रति दुकान सीमित',
  'f.alert.stock.rationed-against-empties': '{name}: सिर्फ़ खाली क्रेट के बदले',
  'f.alert.stock.low': '{name} कम बचा है',
  'f.alert.stock.available': '{name} फिर से स्टॉक में',
  'f.sch.skus': 'पैक',
  'f.sch.allSkus': 'पूरा ऑर्डर',
  'f.sch.threshold': 'लें',
  'f.sch.benefit': 'पाएँ',
  'f.sch.valid': 'अवधि',
  'f.sch.tiers': 'किन दुकानों के लिए',
  'f.sch.allTiers': 'सभी दुकानें',
  'f.sch.cooler': 'कंपनी का कूलर ज़रूरी',
  'f.sch.thrFree': 'एक ऑर्डर में {n} पेटी{pooled}',
  'f.sch.pooled': ' (कोई भी मिलाकर)',
  'f.sch.thrPct': 'एक ऑर्डर में {n} या ज़्यादा पेटी',
  'f.sch.thrFirst': 'पहला ऑर्डर, जुड़ने के {days} दिन के अंदर',
  'f.sch.benFree': '{n} फ़्री पेटी',
  'f.sch.benPct': '{pct}% छूट',
  'f.sch.say': 'दुकानदार को बताएँ',
  'f.sch.sayFree': '"इन पैक की {buy} पेटी लें{mix} और {free} फ़्री पेटी पाएँ। यह डिलीवरी के बाद डिस्ट्रीब्यूटर से मिलती है, आज के बिल में नहीं।"',
  'f.sch.sayMix': ' (कोई भी मिलाकर)',
  'f.sch.sayPct': '"इन पैक की {min} या ज़्यादा पेटी लें और {pct}% छूट पाएँ। डिस्ट्रीब्यूटर बिल में से घटाता है।"',
  'f.sch.sayFirst': '"आपके पहले ऑर्डर पर {pct}% छूट।"',
  'f.stock.status': 'स्टॉक',
  'f.stock.ration': 'सीमा',
  'f.stock.perOutlet': 'प्रति दुकान {n} पेटी',
  'f.stock.note': 'डिस्ट्रीब्यूटर कहता है',
  'f.stock.sync': 'आज {time} पर डिस्ट्रीब्यूटर से। दिन में बदल सकता है।',
  'f.stock.s.available': 'उपलब्ध',
  'f.stock.s.low': 'स्टॉक कम',
  'f.stock.s.rationed': 'सीमित',
  'f.stock.s.rationed-against-empties': 'सिर्फ़ खाली के बदले',
  'f.stock.s.out-of-stock': 'स्टॉक में नहीं',

  // Landing: day, next stop, wins
  'f.home.route': { one: 'आज 1 दुकान', other: 'आज {n} दुकानें' },
  'f.home.done': 'पूरी',
  'f.home.stops': 'आज का रूट',
  'f.home.ordered': 'ऑर्डर · {cases}',
  'f.next.label': 'अगला · स्टॉप {stop}',
  'f.next.open': 'दुकान खोलें',
  'f.next.allDone': 'आज की सभी दुकानें पूरी। काम खत्म होने पर दिन खत्म करें।',
  'f.ms.first': 'दिन का पहला ऑर्डर हो गया!',
  'f.ms.focus3': 'आज 3 दुकानों पर फ़ोकस पैक बिके',
  'f.ms.five': 'आज 5 दुकानों ने ऑर्डर दिया। बढ़िया रफ़्तार!',
  'f.ms.ten': 'आज 10 दुकानों ने ऑर्डर दिया!',
  'f.ms.gain100': 'आज 100 टारगेट पेटी जुड़ीं!',
  'f.ms.step': 'प्री-समर टारगेट {pct}% पार!',

  // Leaderboard
  'f.lb.title': 'लीडरबोर्ड',
  'f.lb.youAre': '{name} (आप)',
  'f.lb.gap': '{name} से {gap} अंक पीछे',
  'f.lb.top': 'आप नंबर 1 हैं। ऐसे ही चलते रहें!',
  'f.lb.you': '{name} (आप)',
  'f.lb.outlets': '{n} दुकानें',
  'f.lb.defs': 'इनका मतलब',
  'f.lb.rep': 'सभी प्रतिनिधि',
  'f.lb.short.preSeasonPct': 'प्री-समर टारगेट',
  'f.lb.short.productiveCallsPct': 'ऑर्डर वाली विज़िट',
  'f.lb.short.activeOutletsPct': 'सक्रिय दुकानें',
  'f.lb.short.focusCoveragePct': 'फ़ोकस पैक दुकानें',
  'f.lb.short.monthTargetPct': 'अप्रैल टारगेट',
  'f.lb.short.casesOrdered': 'पेटी',
  'f.lb.def.preSeasonPct': '1 मार्च से बिकी फ़ोकस पैक पेटी, आपके प्री-समर टारगेट में से।',
  'f.lb.def.productiveCallsPct': 'पिछले 30 दिनों की विज़िट में से कितनी पर ऑर्डर मिला।',
  'f.lb.def.activeOutletsPct': 'पिछले 30 दिनों में कम से कम एक बार ऑर्डर देने वाली दुकानें।',
  'f.lb.def.focusCoveragePct': 'उनमें से कितनी दुकानों ने कम से कम एक फ़ोकस पैक लिया।',
  'f.lb.def.monthTargetPct': 'अप्रैल की पेटी, आपके अप्रैल टारगेट में से।',
  'f.lb.def.casesOrdered': '1 मार्च से बुक की गई सभी पेटी।',

  // Outlet details
  'f.fold.lastLines': 'उन्होंने क्या लिया',
  'f.fold.creditUsed': '{limit} में से {used} इस्तेमाल',
  'f.fold.pays': 'भुगतान',
  'f.fold.cashAbove': 'सीमा से ऊपर नकद',
  'f.fold.cashAboveSub': '{amt} तक उधार',
  'f.fold.recent': 'आख़िरी 3 ऑर्डर',
  'f.fold.today': 'आज',
  'f.fold.company': 'कंपनी का कूलर',
  'f.fold.fits': 'ठंडा रखता है',
  'f.fold.fitsVal': '{n} पेटी',
  'f.fold.fitsSub': '250 ml की',
  'f.fold.outage': 'दोपहर में बिजली जाती है: 2 बजे के बाद ड्रिंक गर्म होते हैं',
  'f.tools.call': 'कॉल',
  'f.tools.callName': '{name} को कॉल करें',
  'f.tools.note': 'नोट लिखें',
  'f.tools.mic': 'बोलकर नोट',
  'f.tools.issue': 'शिकायत दर्ज करें',
  'f.outlet.orderedToday': 'आज ऑर्डर: {cases} · {value}',
  'f.pay.due': '{amt} बकाया',
  'f.pay.room': '{amt} उधार बाकी',
  'f.hist.sum': { one: '1 ऑर्डर', other: '{n} ऑर्डर' },
  'f.book.sum': { one: '1 कार्यक्रम · {cases}', other: '{n} कार्यक्रम · {cases}' },
  'f.notes.sum': { one: '1 नोट', other: '{n} नोट' },
  'f.notes.empty': 'अभी कोई नोट नहीं। ऊपर का नोट या माइक बटन इस्तेमाल करें।',
  'f.sch.head': { one: 'स्कीम · 1 इस्तेमाल हो सकती है', other: 'स्कीम · {n} इस्तेमाल हो सकती हैं' },
  'f.sch.program': 'हर महीने {amt}',
  'f.sch.left': '{month} में {cap} में से {left} फ़्री पेटी बाकी',
  'f.note.title': 'नया नोट',
  'f.note.titleVoice': 'अपना नोट बोलें',
  'f.note.ph': 'जैसे: सुबह 9 बजे तक कूलर भरा। वीकेंड के लिए 2 L बोतलें चाहिए।',
  'f.note.speak': 'बोलने के लिए टैप करें',
  'f.note.listening': 'सुन रहे हैं… रोकने के लिए टैप करें',
  'f.note.noVoice': 'इस ब्राउज़र में आवाज़ नहीं चलती। कृपया टाइप करें।',
  'f.note.micBlocked': 'माइक बंद है। कृपया नोट टाइप करें।',
  'f.note.micFail': 'सुनाई नहीं दिया। फिर कोशिश करें या टाइप करें।',
  'f.note.save': 'नोट सेव करें',
  'f.note.saved': 'नोट सेव हुआ',
  'f.note.voice': 'आवाज़',
  'f.note.call': 'कॉल',
  'f.issue.title': 'दुकानदार की शिकायत',
  'f.issue.ph': 'विवरण लिखें (वैकल्पिक)',
  'f.issue.category': 'किस बारे में है? (एक या ज़्यादा चुनें)',
  'f.issue.save': 'शिकायत सेव करें',
  'f.issue.saved': 'सेव हुआ · {cat}',
  'f.issue.cap': { one: 'खुली शिकायत', other: 'खुली शिकायतें' },
  'f.issue.listTitle': 'इस दुकान की शिकायतें',
  'f.issue.today': 'आज जोड़ी, {time}',
  'f.issue.earlier': 'पहले दर्ज, {date}',
  'f.issue.capLabel': '{n} खुली शिकायतें',
  'f.issue.add': 'शिकायत जोड़ें',
  'f.issue.resolve': 'हल हुई',
  'f.issue.resolved': 'हल',
  'f.issue.cat.scheme': 'स्कीम का पैसा',
  'f.issue.cat.quality': 'माल की क्वालिटी',
  'f.issue.cat.delay': 'देर से डिलीवरी',
  'f.issue.cat.missing': 'कम या टूटा',
  'f.issue.cat.billing': 'कीमत या बिल',
  'f.issue.cat.other': 'अन्य',
  'f.terr.pill': '{name} की दुकान',
  'f.terr.title': 'आपकी दुकान नहीं',
  'f.terr.body': '{name} {rep} ({territory}) की दुकान है।',
  'f.terr.incentive': 'इस ऑर्डर पर आपको सिर्फ़ {pct}% इंसेंटिव मिलेगा। बाकी उस दुकान के प्रतिनिधि को जाएगा।',
  'f.terr.go': 'फिर भी बुक करें ({pct}% इंसेंटिव)',
  'f.terr.back': 'वापस जाएँ',

  // Smart order (the recommendation)
  'f.so.eyebrow': 'सुझाया गया ऑर्डर',
  'f.so.till': '{date} तक काफ़ी',
  'f.so.cases': 'पेटी',
  'f.so.sub': '{date} तक काफ़ी',
  'f.so.subClosing': 'दुकान जल्द बंद होगी। कम या कुछ भी ऑर्डर न करें।',
  'f.so.subNew': 'नई दुकान: कम से शुरू करें, {date} को और जोड़ें',
  'f.so.guess': 'अंदाज़ा',
  'f.so.silent': 'कोई सुझाव नहीं। होलसेलर अपनी योजना से ऑर्डर देते हैं।',
  'f.so.why': 'यह संख्या क्यों',
  'f.so.whatIf': 'अगर 43°C हो जाए तो?',
  'f.so.whatIfOff': 'आज के मौसम पर वापस',
  'f.so.use': 'इन {n} पेटी से ऑर्डर शुरू करें',
  'f.so.r.rate': 'हाल में हफ़्ते में लगभग {n} पेटी बिकीं',
  'f.so.r.bookings': { one: 'अगली डिलीवरी से पहले 1 कार्यक्रम बुक', other: 'अगली डिलीवरी से पहले {n} कार्यक्रम बुक' },
  'f.so.r.peers': 'नए या कम ऑर्डर: {n} मिलती-जुलती दुकानों के आधार पर',
  'f.so.r.seasonUp': 'आगे ज़्यादा बिक्री के दिन',
  'f.so.r.seasonDown': 'आगे कम बिक्री के दिन',
  'f.so.r.seasonPeak': 'पीक सीज़न, पिछले कुछ हफ़्तों जैसा',
  'f.so.r.hot': '{c}°C: आम से ज़्यादा गर्म',
  'f.so.r.normal': '{c}°C: इस समय के लिए सामान्य',
  'f.so.r.onHand': 'दुकान में अभी लगभग {cases} (अंदाज़ा)',
  'f.so.r.closing': '{date} को बंद: {n} बिक्री के दिन बाकी',
  'f.so.r.rain': 'बारिश आ रही है: कम दिनों का ऑर्डर दें',
  'f.so.r.swap': '{from} सीमित: उसकी जगह {to}',
  'f.so.r.out': '{name} स्टॉक में नहीं',
  'f.so.r.ration': '{name}: ज़्यादा से ज़्यादा {n}',
  'f.so.r.cooler': 'कूलर में जितने आएँ उतने ठंडे पैक',
  'f.so.r.creditTrim': 'बचे उधार में आए उतना कम किया',
  'f.so.r.creditCash': 'उधार से {amt} ज़्यादा: नकद लें',
  'f.so.r.cap': '{n} पेटी से कम रखा (सुरक्षित सीमा)',
  'f.so.r.today': 'आज पहले ही {cases} ऑर्डर',
  'f.so.r.newOutlet': 'पहला ऑर्डर: अभी 80%, {date} को और जोड़ें',
  'f.so.chip': 'सुझाए गए',
  'f.so.liveTitle': 'सुझाव: {n} पेटी',
  'f.so.inCart': 'कार्ट में {target} में से {have}',
  'f.so.addAll': 'सब जोड़ें',
  'f.so.allGood': 'अच्छा ऑर्डर। दुकान जितना बेचेगी उतना ही।',
  'f.so.skuHint': 'सुझाव {n}',
  'f.so.skuShelf': 'दुकान में {n}',
  'f.so.badge': 'ऑर्डर ~{n}',
  'f.so.badgeClosing': 'जल्द बंद',

  // Why this pack (New order, under each suggested pack)
  'f.why.qty': '{n} पेटी सुझाई गईं',
  'f.why.tLow': 'स्टॉक कम',
  'f.why.tExtra': 'ज़्यादा बिक्री का मौका',
  'f.why.tMissing': 'शेल्फ पर नहीं',
  'f.why.tRefill': 'नियमित भराई',
  'f.why.tPeers': 'मिलती दुकानों में बिकता है',
  'f.why.tBookings': 'बुक कार्यक्रमों के लिए',
  'f.why.lLow': 'लगभग {left} बचा, हफ़्ते में ~{n} बिकता है',
  'f.why.lExtra': '+{pct}% बिक्री की उम्मीद: आगे गर्म दिन',
  'f.why.lLowNone': 'लगभग खत्म, हफ़्ते में ~{n} बिकता है',
  'f.why.lMissing': 'आख़िरी ऑर्डर {date}, शायद खत्म',
  'f.why.lNever': 'हाल के ऑर्डर में नहीं, यहाँ अच्छा बिकता है',
  'f.why.lRefill': 'यहाँ हफ़्ते में ~{n} बिकता है',
  'f.why.lRefillOh': 'हफ़्ते में ~{n} बिकता है, दुकान में ~{oh} बचा',
  'f.why.lPeers': 'ऐसी दुकानें हफ़्ते में ~{n} बेचती हैं',
  'f.why.lBookings': 'बुक कार्यक्रमों के लिए काफ़ी',
  'f.why.fRate': 'यहाँ हफ़्ते में लगभग {n} पेटी बिकती हैं (पिछले 4 हफ़्ते)',
  'f.why.fPeers': 'पास की मिलती दुकानें हफ़्ते में लगभग {n} पेटी बेचती हैं',
  'f.why.fBookings': 'अगली डिलीवरी से पहले बुक कार्यक्रमों के आधार पर',
  'f.why.fExpected': '{date} तक लगभग {n} पेटी बिकने का अनुमान',
  'f.why.fLift': '{date} तक लगभग {n} पेटी बिकने का अनुमान (गर्मी और सीज़न से +{pct}%)',
  'f.why.fLeft': 'दुकान में अभी लगभग {n} पेटी (अंदाज़ा), इसलिए कम ऑर्डर',
  'f.why.fCounted': 'शेल्फ पर {n} पेटी (आपने गिनीं), इसलिए कम ऑर्डर',
  'f.why.fLast': 'आख़िरी ऑर्डर: {date} को {n} पेटी',
  'f.why.fRation': 'डिस्ट्रीब्यूटर प्रति दुकान सिर्फ़ {n} देता है',
  'f.why.fCooler': 'कूलर में जितना आए उतना किया',
  'f.why.fCredit': 'बचे उधार में आए उतना किया',
  'f.why.fCap': 'इस दुकान की सुरक्षित सीमा से कम रखा',

  // Tips (booking and review)
  'f.type.warning': 'जाँचें',
  'f.type.scheme': 'स्कीम',
  'f.type.reco': 'और जोड़ें',
  'f.type.info': 'नोट',
  'f.tips.more': { one: '1 और सुझाव', other: '{n} और सुझाव' },
  'f.act.add': '{n} जोड़ें',
  'f.act.set': '{n} करें',
  'f.act.swap': 'बदलें',
  'f.act.trim': 'कम करें',
  'f.tip.out': '{name} स्टॉक में नहीं। हटा दें।',
  'f.tip.outSwap': '{name} स्टॉक में नहीं। उसकी जगह {n} {alt} दें।',
  'f.tip.ration': 'सिर्फ़ {n} {name} चलेंगे। {move} {alt} में डालें।',
  'f.tip.rationOnly': 'प्रति दुकान सिर्फ़ {n} {name} चलेंगे।',
  'f.tip.pace': '{n} और {name} जोड़ें। {date} तक बिक जाएगा।',
  'f.tip.regular': '{name} नहीं है। वे लगभग हर बार लेते हैं।',
  'f.tip.thresholdFree': '{n} और {name} = 1 फ़्री पेटी ({scheme})',
  'f.tip.thresholdPct': '{n} और {name} = {pct}% छूट ({scheme})',
  'f.tip.cap': '{scheme}: इस महीने की फ़्री पेटी खत्म',
  'f.tip.larger': 'आम से बहुत बड़ा: {n} पेटी, दुकान को लगभग {need} चाहिए',
  'f.tip.cooler': 'ठंडे पैक ज़्यादा। कूलर में लगभग {n} पेटी ही आती हैं।',
  'f.tip.noCooler': 'यहाँ कूलर नहीं। ठंडे पैक कम रखें, बड़ी बोतलें बेचें।',
  'f.tip.closing': 'दुकान जल्द बंद: सिर्फ़ {n} बिक्री के दिन बाकी।',
  'f.tip.shelf': '{name}: {days} दिन का स्टॉक। बिकने से पहले खराब होगा।',
  'f.tip.cover': '{name}: {days} दिन का स्टॉक। बहुत ज़्यादा, कम करें।',
  'f.tip.together': 'पास की जो दुकानें {with} लेती हैं वे {name} भी लेती हैं ({pct}%)',
  'f.rc.title': 'सबमिट करने से पहले',
  'f.rc.ok': 'अच्छा ऑर्डर। {date} तक दुकान जितना बेचेगी उतना ही।',
  'f.offer.titleScheme': 'नमस्ते {name}! यह ऑफ़र मत छोड़िए',
  'f.offer.titleReco': 'नमस्ते {name}! एक और चीज़ जो बिकती है',
  'f.offer.add': '{n} {name} जोड़ें',
  'f.offer.addCases': '{n} पेटी जोड़ें',

  // The scheme picked with "Book with this scheme"
  'f.fs.count': 'कार्ट में {need} में से {have} स्कीम पेटी',
  'f.fs.met': 'स्कीम पूरी',
  'f.fs.free': '{packs} में से {n} और जोड़ें और {free} फ़्री पेटी पाएँ ({name})।',
  'f.fs.pct': '{packs} में से {n} और जोड़ें और {pct}% छूट पाएँ ({name})।',
  'f.offer.skip': 'अभी नहीं',

  // After submit
  'f.saved.order': 'ऑर्डर · {cases} · {value}',
  'f.saved.gain': 'प्री-समर टारगेट में +{n} पेटी',
  'f.saved.noGain': 'इस ऑर्डर में फ़ोकस पैक नहीं, इसलिए प्री-समर टारगेट नहीं बदला',
  'f.out.title': 'इस दुकान पर अगला हफ़्ता',
  'f.out.dir.up': 'बिक्री बढ़ने की संभावना',
  'f.out.dir.down': 'बिक्री घटने की संभावना',
  'f.out.dir.steady': 'बिक्री ऊँची रहने की संभावना',
  'f.out.next': 'अगली विज़िट {date} · लगभग {n} पेटी',
  'f.out.top': 'टॉप पैक: {list}',
  'f.out.stock': 'डिस्ट्रीब्यूटर के पास {list} कम है',
  'f.out.prep': { one: 'तैयारी के लिए 1 बात', other: 'तैयारी के लिए {n} बातें' },
  'f.out.prepClosure': '{date} से दुकान बंद: छोटा आख़िरी ऑर्डर तय करें',
  'f.out.prepBookings': { one: '1 कार्यक्रम बुक: अगली विज़िट पर पक्का करें', other: '{n} कार्यक्रम बुक: अगली विज़िट पर पक्के करें' },
  'f.out.prepStock': 'डिस्ट्रीब्यूटर से {list} के बारे में पूछें',
  'f.out.prepRain': 'बारिश की संभावना: अगला ऑर्डर छोटा रखें',
  'f.out.prepCall': '{date} को मालिक को कॉल करें',

  // Booking: SKU details
  'f.sku.ration': 'सीमित · प्रति दुकान {n}',
  'f.sku.sIn': 'स्टॉक में',
  'f.sku.sMax': 'अधिकतम {n}',
  'f.sku.sEmpties': 'सिर्फ़ खाली पर',
  'f.sku.sLow': 'स्टॉक कम',
  'f.sku.sOut': 'स्टॉक नहीं',
  'f.sku.details': 'विवरण',
  'f.sku.newer': 'नया पैक',
  'f.sku.shelf': 'शेल्फ लाइफ',
  'f.sku.shelfDays': '{n} दिन',
  'f.sku.focus': 'फ़ोकस पैक',
  'f.sku.focusYes': 'हाँ · प्री-समर टारगेट में गिना जाता है',
  'f.sku.alt': 'स्टॉक में नहीं। उसकी जगह {name} दें।',
  'f.sku.outHint': 'डिस्ट्रीब्यूटर के पास स्टॉक नहीं',
  'f.sku.overRation': 'प्रति दुकान सिर्फ़ {n} पेटी चलेंगी',
  'f.sku.evTitle': 'दुकानें इसे क्यों ले रही हैं',
  'f.sku.evBuyers': '{area} की दुकानों ने {weeks} हफ़्तों में लिया ({cases} पेटी)',
  'f.sku.evGrew': 'उनमें से पिछले साल से ज़्यादा लिया',
  'f.sku.evOfftake': '{region} में {weeks} हफ़्तों में ग्राहकों को {unit} बिकीं',
  'f.sku.demoEv': 'डेमो',
};
