// Marathi text for the field features (keys start with "f."), same keys as strings-en.js.
// Merged into STRINGS.mr by js/strings.js. Simple spoken Marathi; pack names stay as they are.

export const FIELD_MR = {
  'f.common.ok': 'ठीक आहे',

  // Login
  'f.login.title': 'आजच्या रूटसाठी तयार?',
  'f.login.show': 'दाखवा',
  'f.login.hide': 'लपवा',
  'f.login.demo': 'डेमो: कोणतेही नाव आणि पासवर्ड चालेल.',

  // Landing: header
  'f.clock.in': 'दिवस सुरू करा',
  'f.clock.out': 'संपवा',
  'f.clock.onFor': 'ड्युटीवर · {dur}',
  'f.clock.dayDone': 'दिवस पूर्ण · {dur}',
  'f.clock.hm': '{h}ता {m}मि',
  'f.clock.m': '{m} मि',
  'f.clock.inToast': 'दिवस {time} ला सुरू झाला',
  'f.clock.outToast': 'दिवस संपला · {dur} ड्युटी',
  'f.rank.chip': '{total} पैकी {rank} वा',
  'f.target.title': 'प्री-समर टार्गेट',
  'f.target.cases': 'पेट्या',
  'f.target.today': 'आज',
  'f.target.daysLeft': { one: '1 दिवस बाकी', other: '{n} दिवस बाकी' },
  'f.target.pace': 'पूर्ण करण्यासाठी रोज सुमारे {n} पेट्या विका',
  'f.target.done': 'टार्गेट पूर्ण! प्रत्येक जास्त पेटी तुमची आघाडी वाढवते.',
  'f.target.counts': 'समर SKU: {skus}',
  'f.target.window': '{from} ते {to}',
  'f.target.month': 'एप्रिल टार्गेट',

  // Landing: alerts and the updates screen
  'f.alert.head': { one: 'आजची 1 अपडेट', other: 'आजच्या {n} अपडेट्स' },
  'f.alert.viewAll': 'अपडेट्स पहा',
  'f.alert.none': 'नवीन अपडेट नाही',
  'f.alert.tagOut': 'स्टॉक संपला',
  'f.alert.tagLow': 'स्टॉक कमी',
  'f.upd.title': 'अपडेट्स',
  'f.upd.unread': { one: '1 अजून उघडली नाही', other: '{n} अजून उघडल्या नाहीत' },
  'f.upd.stock': 'डिस्ट्रिब्युटर स्टॉक',
  'f.upd.schemes': 'स्कीम',
  'f.alert.view': 'पहा',
  'f.alert.tagNew': 'नवीन स्कीम',
  'f.alert.tagSoon': 'स्कीम लवकरच',
  'f.alert.tagUp': 'स्टॉक परत आला',
  'f.alert.tagDown': 'स्टॉक अलर्ट',
  'f.alert.from': '{date} पासून',
  'f.alert.till': '{date} पर्यंत',
  'f.alert.rationUp': '{name}: मर्यादा वाढून प्रति दुकान {n}',
  'f.alert.rationDown': '{name}: मर्यादा कमी होऊन प्रति दुकान {n}',
  'f.alert.stock.out-of-stock': '{name} स्टॉकमध्ये नाही',
  'f.alert.stock.rationed': '{name}: प्रति दुकान मर्यादित',
  'f.alert.stock.rationed-against-empties': '{name}: फक्त रिकाम्या क्रेटच्या बदल्यात',
  'f.alert.stock.low': '{name} कमी उरले आहे',
  'f.alert.stock.available': '{name} परत स्टॉकमध्ये',
  'f.sch.skus': 'पॅक',
  'f.sch.allSkus': 'संपूर्ण ऑर्डर',
  'f.sch.threshold': 'घ्या',
  'f.sch.benefit': 'मिळवा',
  'f.sch.valid': 'कालावधी',
  'f.sch.tiers': 'कोणत्या दुकानांना',
  'f.sch.allTiers': 'सर्व दुकाने',
  'f.sch.cooler': 'कंपनीचा कूलर हवा',
  'f.sch.thrFree': 'एका ऑर्डरमध्ये {n} पेट्या{pooled}',
  'f.sch.pooled': ' (कोणतेही मिश्रण)',
  'f.sch.thrPct': 'एका ऑर्डरमध्ये {n} किंवा जास्त पेट्या',
  'f.sch.thrFirst': 'पहिली ऑर्डर, जोडल्यापासून {days} दिवसांत',
  'f.sch.benFree': '{n} मोफत पेटी',
  'f.sch.benPct': '{pct}% सूट',
  'f.sch.say': 'दुकानदाराला सांगा',
  'f.sch.sayFree': '"या पॅकच्या {buy} पेट्या घ्या{mix} आणि {free} मोफत पेटी मिळवा. ती डिलिव्हरीनंतर डिस्ट्रिब्युटरकडून मिळते, आजच्या बिलात नाही."',
  'f.sch.sayMix': ' (कोणतेही मिश्रण)',
  'f.sch.sayPct': '"या पॅकच्या {min} किंवा जास्त पेट्या घ्या आणि {pct}% सूट मिळवा. डिस्ट्रिब्युटर बिलातून कमी करतो."',
  'f.sch.sayFirst': '"तुमच्या पहिल्या ऑर्डरवर {pct}% सूट."',
  'f.stock.status': 'स्टॉक',
  'f.stock.ration': 'मर्यादा',
  'f.stock.perOutlet': 'प्रति दुकान {n} पेट्या',
  'f.stock.note': 'डिस्ट्रिब्युटर म्हणतो',
  'f.stock.sync': 'आज {time} ला डिस्ट्रिब्युटरकडून. दिवसभरात बदलू शकते.',
  'f.stock.s.available': 'उपलब्ध',
  'f.stock.s.low': 'स्टॉक कमी',
  'f.stock.s.rationed': 'मर्यादित',
  'f.stock.s.rationed-against-empties': 'फक्त रिकाम्यांच्या बदल्यात',
  'f.stock.s.out-of-stock': 'स्टॉकमध्ये नाही',

  // Landing: day, next stop, wins
  'f.home.route': { one: 'आज 1 दुकान', other: 'आज {n} दुकाने' },
  'f.home.done': 'पूर्ण',
  'f.home.stops': 'आजचा रूट',
  'f.home.ordered': 'ऑर्डर · {cases}',
  'f.next.label': 'पुढचे · थांबा {stop}',
  'f.next.open': 'दुकान उघडा',
  'f.next.allDone': 'आजची सर्व दुकाने पूर्ण. काम संपल्यावर दिवस संपवा.',
  'f.ms.first': 'दिवसाची पहिली ऑर्डर झाली!',
  'f.ms.focus3': 'आज 3 दुकानांत फोकस पॅक विकले',
  'f.ms.five': 'आज 5 दुकानांनी ऑर्डर दिली. छान वेग!',
  'f.ms.ten': 'आज 10 दुकानांनी ऑर्डर दिली!',
  'f.ms.gain100': 'आज 100 टार्गेट पेट्या जोडल्या!',
  'f.ms.step': 'प्री-समर टार्गेट {pct}% पार!',

  // Leaderboard
  'f.lb.title': 'लीडरबोर्ड',
  'f.lb.youAre': '{name} (तुम्ही)',
  'f.lb.gap': '{name} पेक्षा {gap} गुण मागे',
  'f.lb.top': 'तुम्ही नंबर 1 आहात. असेच चालू ठेवा!',
  'f.lb.you': '{name} (तुम्ही)',
  'f.lb.outlets': '{n} दुकाने',
  'f.lb.defs': 'याचा अर्थ काय',
  'f.lb.rep': 'सर्व प्रतिनिधी',
  'f.lb.short.preSeasonPct': 'प्री-समर टार्गेट',
  'f.lb.short.productiveCallsPct': 'ऑर्डर मिळालेल्या भेटी',
  'f.lb.short.activeOutletsPct': 'सक्रिय दुकाने',
  'f.lb.short.focusCoveragePct': 'फोकस पॅक दुकाने',
  'f.lb.short.monthTargetPct': 'एप्रिल टार्गेट',
  'f.lb.short.casesOrdered': 'पेट्या',
  'f.lb.def.preSeasonPct': '1 मार्चपासून विकलेल्या फोकस पॅक पेट्या, तुमच्या प्री-समर टार्गेटपैकी.',
  'f.lb.def.productiveCallsPct': 'मागील 30 दिवसांच्या भेटींपैकी किती भेटींत ऑर्डर मिळाली.',
  'f.lb.def.activeOutletsPct': 'मागील 30 दिवसांत किमान एकदा ऑर्डर दिलेली दुकाने.',
  'f.lb.def.focusCoveragePct': 'त्यापैकी किती दुकानांनी किमान एक फोकस पॅक घेतला.',
  'f.lb.def.monthTargetPct': 'एप्रिलच्या पेट्या, तुमच्या एप्रिल टार्गेटपैकी.',
  'f.lb.def.casesOrdered': '1 मार्चपासून बुक केलेल्या सर्व पेट्या.',

  // Outlet details
  'f.fold.lastLines': 'त्यांनी काय घेतले',
  'f.fold.creditUsed': '{limit} पैकी {used} वापरले',
  'f.fold.pays': 'पेमेंट',
  'f.fold.cashAbove': 'मर्यादेवर रोख',
  'f.fold.cashAboveSub': '{amt} पर्यंत उधार',
  'f.fold.recent': 'शेवटच्या 3 ऑर्डर',
  'f.fold.today': 'आज',
  'f.fold.company': 'कंपनीचा कूलर',
  'f.fold.fits': 'थंड बसतात',
  'f.fold.fitsVal': '{n} पेट्या',
  'f.fold.fitsSub': '250 ml च्या',
  'f.fold.outage': 'दुपारी वीज जाते: 2 नंतर ड्रिंक्स गरम होतात',
  'f.tools.call': 'कॉल',
  'f.tools.callName': '{name} ला कॉल करा',
  'f.tools.note': 'नोट लिहा',
  'f.tools.mic': 'बोलून नोट',
  'f.tools.issue': 'तक्रार नोंदवा',
  'f.outlet.orderedToday': 'आज ऑर्डर: {cases} · {value}',
  'f.pay.due': '{amt} थकबाकी',
  'f.pay.room': '{amt} उधार बाकी',
  'f.hist.sum': { one: '1 ऑर्डर', other: '{n} ऑर्डर' },
  'f.book.sum': { one: '1 कार्यक्रम · {cases}', other: '{n} कार्यक्रम · {cases}' },
  'f.notes.sum': { one: '1 नोट', other: '{n} नोट्स' },
  'f.notes.empty': 'अजून नोट नाही. वरचे नोट किंवा माइक बटण वापरा.',
  'f.sch.head': { one: 'स्कीम · 1 वापरता येते', other: 'स्कीम · {n} वापरता येतात' },
  'f.sch.program': 'दरमहा {amt}',
  'f.sch.left': '{month} मध्ये {cap} पैकी {left} मोफत पेट्या बाकी',
  'f.note.title': 'नवीन नोट',
  'f.note.titleVoice': 'तुमची नोट बोला',
  'f.note.ph': 'उदा. सकाळी 9 पर्यंत कूलर भरलेला. वीकेंडसाठी 2 L बाटल्या हव्या.',
  'f.note.speak': 'बोलण्यासाठी टॅप करा',
  'f.note.listening': 'ऐकत आहे… थांबवण्यासाठी टॅप करा',
  'f.note.noVoice': 'या ब्राउझरमध्ये आवाज चालत नाही. कृपया टाइप करा.',
  'f.note.micBlocked': 'माइक बंद आहे. कृपया नोट टाइप करा.',
  'f.note.micFail': 'ऐकू आले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.',
  'f.note.save': 'नोट सेव्ह करा',
  'f.note.saved': 'नोट सेव्ह झाली',
  'f.note.voice': 'आवाज',
  'f.note.call': 'कॉल',
  'f.issue.title': 'दुकानदाराची तक्रार',
  'f.issue.ph': 'तपशील लिहा (ऐच्छिक)',
  'f.issue.category': 'कशाबद्दल आहे? (एक किंवा जास्त निवडा)',
  'f.issue.save': 'तक्रार सेव्ह करा',
  'f.issue.saved': 'सेव्ह झाले · {cat}',
  'f.issue.cap': { one: 'उघडी तक्रार', other: 'उघड्या तक्रारी' },
  'f.issue.listTitle': 'या दुकानाच्या तक्रारी',
  'f.issue.today': 'आज जोडली, {time}',
  'f.issue.earlier': 'आधी नोंदवली, {date}',
  'f.issue.capLabel': '{n} उघड्या तक्रारी',
  'f.issue.add': 'तक्रार जोडा',
  'f.issue.resolve': 'सुटली म्हणून नोंदवा',
  'f.issue.resolved': 'सुटली',
  'f.issue.cat.scheme': 'स्कीमचे पैसे',
  'f.issue.cat.quality': 'मालाचा दर्जा',
  'f.issue.cat.delay': 'उशिरा डिलिव्हरी',
  'f.issue.cat.missing': 'कमी किंवा फुटलेले',
  'f.issue.cat.billing': 'किंमत किंवा बिल',
  'f.issue.cat.other': 'इतर',
  'f.terr.pill': '{name} चे दुकान',
  'f.terr.title': 'तुमचे दुकान नाही',
  'f.terr.body': '{name} हे {rep} ({territory}) यांचे दुकान आहे.',
  'f.terr.incentive': 'या ऑर्डरवर तुम्हाला फक्त {pct}% इन्सेंटिव्ह मिळेल. बाकी त्या दुकानाच्या प्रतिनिधीला जाईल.',
  'f.terr.go': 'तरीही बुक करा ({pct}% इन्सेंटिव्ह)',
  'f.terr.back': 'मागे जा',

  // Smart order (the recommendation)
  'f.so.eyebrow': 'सुचवलेली ऑर्डर',
  'f.so.till': '{date} पर्यंत पुरेल',
  'f.so.cases': 'पेट्या',
  'f.so.sub': '{date} पर्यंत पुरेल',
  'f.so.subClosing': 'दुकान लवकरच बंद होणार. कमी किंवा काहीच ऑर्डर नको.',
  'f.so.subNew': 'नवीन दुकान: कमी सुरुवात करा, {date} ला अजून जोडा',
  'f.so.guess': 'अंदाज',
  'f.so.silent': 'सूचना नाही. होलसेलर स्वतःच्या नियोजनाने ऑर्डर देतात.',
  'f.so.why': 'हा आकडा का',
  'f.so.whatIf': '43°C झाले तर?',
  'f.so.whatIfOff': 'आजच्या हवामानावर परत',
  'f.so.use': 'या {n} पेट्यांनी ऑर्डर सुरू करा',
  'f.so.r.rate': 'अलीकडे आठवड्याला सुमारे {n} पेट्या विकल्या',
  'f.so.r.bookings': { one: 'पुढच्या डिलिव्हरीआधी 1 कार्यक्रम बुक', other: 'पुढच्या डिलिव्हरीआधी {n} कार्यक्रम बुक' },
  'f.so.r.peers': 'नवीन किंवा कमी ऑर्डर: {n} सारख्या दुकानांवरून',
  'f.so.r.seasonUp': 'पुढे जास्त गर्दीचे दिवस',
  'f.so.r.seasonDown': 'पुढे कमी विक्रीचे दिवस',
  'f.so.r.seasonPeak': 'पीक सीझन, मागील काही आठवड्यांसारखा',
  'f.so.r.hot': '{c}°C: नेहमीपेक्षा जास्त उष्ण',
  'f.so.r.normal': '{c}°C: या वेळेसाठी सामान्य',
  'f.so.r.onHand': 'दुकानात अजून सुमारे {cases} (अंदाज)',
  'f.so.r.closing': '{date} ला बंद: {n} विक्रीचे दिवस बाकी',
  'f.so.r.rain': 'पाऊस येतोय: कमी दिवसांसाठी ऑर्डर द्या',
  'f.so.r.swap': '{from} मर्यादित: त्याऐवजी {to}',
  'f.so.r.out': '{name} स्टॉकमध्ये नाही',
  'f.so.r.ration': '{name}: जास्तीत जास्त {n}',
  'f.so.r.cooler': 'कूलरमध्ये बसतील इतके थंड पॅक',
  'f.so.r.creditTrim': 'बाकी उधारीत बसेल इतके कमी केले',
  'f.so.r.creditCash': 'उधारीपेक्षा {amt} जास्त: रोख घ्या',
  'f.so.r.cap': '{n} पेट्यांखाली ठेवले (सुरक्षित मर्यादा)',
  'f.so.r.today': 'आज आधीच {cases} ऑर्डर',
  'f.so.r.newOutlet': 'पहिली ऑर्डर: आता 80%, {date} ला अजून जोडा',
  'f.so.chip': 'सुचवलेले',
  'f.so.liveTitle': 'सुचवलेले: {n} पेट्या',
  'f.so.inCart': 'कार्टमध्ये {target} पैकी {have}',
  'f.so.addAll': 'सर्व जोडा',
  'f.so.allGood': 'चांगली ऑर्डर. दुकान जितके विकेल तितकीच.',
  'f.so.skuHint': 'सुचवलेले {n}',
  'f.so.skuShelf': 'दुकानात {n}',
  'f.so.badge': 'ऑर्डर ~{n}',
  'f.so.badgeClosing': 'लवकरच बंद',

  // Why this pack (New order, under each suggested pack)
  'f.why.qty': '{n} पेट्या सुचवलेल्या',
  'f.why.tLow': 'स्टॉक कमी',
  'f.why.tExtra': 'जास्त विक्रीची संधी',
  'f.why.tMissing': 'शेल्फवर नाही',
  'f.why.tRefill': 'नेहमीची भरती',
  'f.why.tPeers': 'सारख्या दुकानांत विकते',
  'f.why.tBookings': 'बुक कार्यक्रमांसाठी',
  'f.why.lLow': 'सुमारे {left} बाकी, आठवड्याला ~{n} विकतात',
  'f.why.lExtra': '+{pct}% विक्री अपेक्षित: पुढे उष्ण दिवस',
  'f.why.lLowNone': 'जवळजवळ संपले, आठवड्याला ~{n} विकतात',
  'f.why.lMissing': 'शेवटची ऑर्डर {date}, बहुधा संपले',
  'f.why.lNever': 'अलीकडच्या ऑर्डरमध्ये नाही, इथे चांगले विकते',
  'f.why.lRefill': 'इथे आठवड्याला ~{n} विकतात',
  'f.why.lRefillOh': 'आठवड्याला ~{n} विकतात, दुकानात ~{oh} बाकी',
  'f.why.lPeers': 'अशी दुकाने आठवड्याला ~{n} विकतात',
  'f.why.lBookings': 'बुक कार्यक्रमांसाठी पुरेसे',
  'f.why.fRate': 'इथे आठवड्याला सुमारे {n} पेट्या विकतात (मागील 4 आठवडे)',
  'f.why.fPeers': 'जवळची सारखी दुकाने आठवड्याला सुमारे {n} पेट्या विकतात',
  'f.why.fBookings': 'पुढच्या डिलिव्हरीआधी बुक कार्यक्रमांवरून',
  'f.why.fExpected': '{date} पर्यंत सुमारे {n} पेट्या विकण्याचा अंदाज',
  'f.why.fLift': '{date} पर्यंत सुमारे {n} पेट्या विकण्याचा अंदाज (उष्णता आणि सीझनमुळे +{pct}%)',
  'f.why.fLeft': 'दुकानात अजून सुमारे {n} पेट्या (अंदाज), म्हणून कमी ऑर्डर',
  'f.why.fCounted': 'शेल्फवर {n} पेट्या (तुम्ही मोजल्या), म्हणून कमी ऑर्डर',
  'f.why.fLast': 'शेवटची ऑर्डर: {date} ला {n} पेट्या',
  'f.why.fRation': 'डिस्ट्रिब्युटर प्रति दुकान फक्त {n} देतो',
  'f.why.fCooler': 'कूलरमध्ये बसेल इतके कमी केले',
  'f.why.fCredit': 'बाकी उधारीत बसेल इतके कमी केले',
  'f.why.fCap': 'या दुकानाच्या सुरक्षित मर्यादेखाली ठेवले',

  // Tips (booking and review)
  'f.type.warning': 'तपासा',
  'f.type.scheme': 'स्कीम',
  'f.type.reco': 'अजून जोडा',
  'f.type.info': 'नोंद',
  'f.tips.more': { one: 'अजून 1 सूचना', other: 'अजून {n} सूचना' },
  'f.act.add': '{n} जोडा',
  'f.act.set': '{n} करा',
  'f.act.swap': 'बदला',
  'f.act.trim': 'कमी करा',
  'f.tip.out': '{name} स्टॉकमध्ये नाही. काढून टाका.',
  'f.tip.outSwap': '{name} स्टॉकमध्ये नाही. त्याऐवजी {n} {alt} द्या.',
  'f.tip.ration': 'फक्त {n} {name} चालतील. {move} {alt} मध्ये हलवा.',
  'f.tip.rationOnly': 'प्रति दुकान फक्त {n} {name} चालतील.',
  'f.tip.pace': 'अजून {n} {name} जोडा. {date} पर्यंत विकले जाईल.',
  'f.tip.regular': '{name} नाही. ते जवळजवळ प्रत्येक वेळी घेतात.',
  'f.tip.thresholdFree': 'अजून {n} {name} = 1 मोफत पेटी ({scheme})',
  'f.tip.thresholdPct': 'अजून {n} {name} = {pct}% सूट ({scheme})',
  'f.tip.cap': '{scheme}: या महिन्याच्या मोफत पेट्या संपल्या',
  'f.tip.larger': 'नेहमीपेक्षा खूप मोठी: {n} पेट्या, दुकानाला सुमारे {need} लागतील',
  'f.tip.cooler': 'थंड पॅक जास्त. कूलरमध्ये सुमारे {n} पेट्याच बसतात.',
  'f.tip.noCooler': 'इथे कूलर नाही. थंड पॅक कमी ठेवा, मोठ्या बाटल्या विका.',
  'f.tip.closing': 'दुकान लवकरच बंद: फक्त {n} विक्रीचे दिवस बाकी.',
  'f.tip.shelf': '{name}: {days} दिवसांचा स्टॉक. विकण्याआधी खराब होईल.',
  'f.tip.cover': '{name}: {days} दिवसांचा स्टॉक. खूप जास्त, कमी करा.',
  'f.tip.together': 'जवळची दुकाने जी {with} घेतात ती {name} पण घेतात ({pct}%)',
  'f.rc.title': 'सबमिट करण्याआधी',
  'f.rc.ok': 'चांगली ऑर्डर. {date} पर्यंत दुकान जितके विकेल तितकीच.',
  'f.offer.titleScheme': 'नमस्कार {name}! ही ऑफर सोडू नका',
  'f.offer.titleReco': 'नमस्कार {name}! अजून एक विकणारी गोष्ट',
  'f.offer.add': '{n} {name} जोडा',
  'f.offer.addCases': '{n} पेट्या जोडा',

  // The scheme picked with "Book with this scheme"
  'f.fs.count': 'कार्टमध्ये {need} पैकी {have} स्कीम पेट्या',
  'f.fs.met': 'स्कीम पूर्ण',
  'f.fs.free': '{packs} पैकी अजून {n} जोडा आणि {free} मोफत पेटी मिळवा ({name}).',
  'f.fs.pct': '{packs} पैकी अजून {n} जोडा आणि {pct}% सूट मिळवा ({name}).',
  'f.offer.skip': 'आत्ता नको',

  // After submit
  'f.saved.order': 'ऑर्डर · {cases} · {value}',
  'f.saved.gain': 'प्री-समर टार्गेटमध्ये +{n} पेट्या',
  'f.saved.gainTail': 'पेट्या प्री-समर टार्गेटमध्ये',
  'f.saved.noGain': 'या ऑर्डरमध्ये फोकस पॅक नाहीत, त्यामुळे प्री-समर टार्गेट बदलले नाही',
  'f.out.title': 'या दुकानात पुढचा आठवडा',
  'f.out.dir.up': 'विक्री वाढण्याची शक्यता',
  'f.out.dir.down': 'विक्री कमी होण्याची शक्यता',
  'f.out.dir.steady': 'विक्री जास्तच राहण्याची शक्यता',
  'f.out.next': 'पुढची भेट {date} · सुमारे {n} पेट्या',
  'f.out.top': 'टॉप पॅक: {list}',
  'f.out.stock': 'डिस्ट्रिब्युटरकडे {list} कमी आहे',
  'f.out.prep': { one: 'तयारीसाठी 1 गोष्ट', other: 'तयारीसाठी {n} गोष्टी' },
  'f.out.prepClosure': '{date} पासून दुकान बंद: छोटी शेवटची ऑर्डर ठरवा',
  'f.out.prepBookings': { one: '1 कार्यक्रम बुक: पुढच्या भेटीत पक्का करा', other: '{n} कार्यक्रम बुक: पुढच्या भेटीत पक्के करा' },
  'f.out.prepStock': 'डिस्ट्रिब्युटरला {list} बद्दल विचारा',
  'f.out.prepRain': 'पावसाची शक्यता: पुढची ऑर्डर छोटी ठेवा',
  'f.out.prepCall': '{date} ला मालकाला कॉल करा',

  // Booking: SKU details
  'f.sku.ration': 'मर्यादित · प्रति दुकान {n}',
  'f.sku.sIn': 'स्टॉकमध्ये',
  'f.sku.sMax': 'कमाल {n}',
  'f.sku.sEmpties': 'फक्त रिकाम्यांवर',
  'f.sku.sLow': 'स्टॉक कमी',
  'f.sku.sOut': 'स्टॉक नाही',
  'f.sku.details': 'तपशील',
  'f.sku.newer': 'नवीन पॅक',
  'f.sku.shelf': 'शेल्फ लाइफ',
  'f.sku.shelfDays': '{n} दिवस',
  'f.sku.focus': 'फोकस पॅक',
  'f.sku.focusYes': 'हो · प्री-समर टार्गेटमध्ये मोजले जाते',
  'f.sku.alt': 'स्टॉकमध्ये नाही. त्याऐवजी {name} द्या.',
  'f.sku.outHint': 'डिस्ट्रिब्युटरकडे स्टॉक नाही',
  'f.sku.overRation': 'प्रति दुकान फक्त {n} पेट्या चालतील',
  'f.sku.evTitle': 'दुकाने हे का घेत आहेत',
  'f.sku.evBuyers': '{area} मधील दुकानांनी {weeks} आठवड्यांत घेतले ({cases} पेट्या)',
  'f.sku.evGrew': 'त्यापैकी मागील वर्षापेक्षा जास्त घेतले',
  'f.sku.evOfftake': '{region} मध्ये {weeks} आठवड्यांत ग्राहकांना {unit} विकल्या',
  'f.sku.demoEv': 'डेमो',
};
