// English text for the field-assistant features (keys start with "f."). Merged into
// STRINGS.en by js/strings.js. Marathi and Hindi fall back to English until translated.

export const FIELD_EN = {
  // clock in / out
  'f.clock.in': 'Clock in',
  'f.clock.out': 'Clock out',
  'f.clock.again': 'Clock in again',
  'f.clock.on': 'On duty',
  'f.clock.since': 'since {time} · {dur}',
  'f.clock.notYet': 'Not clocked in yet',
  'f.clock.closed': 'Day closed · {from}–{to} · {dur}',
  'f.clock.hm': '{h} h {m} min',
  'f.clock.m': '{m} min',
  'f.clock.inToast': 'Clocked in at {time}',
  'f.clock.outToast': 'Clocked out · {dur} on duty',

  // alerts
  'f.alert.schemeNew': 'New scheme: {name} · active since {date}',
  'f.alert.schemeSoon': 'Scheme starting {date}: {name}',
  'f.alert.rationUp': '{name}: ration raised to {n} cases per outlet',
  'f.alert.rationDown': '{name}: ration cut to {n} cases per outlet',
  'f.alert.stock.out-of-stock': '{name} is out of stock at the distributor',
  'f.alert.stock.rationed': '{name} is now rationed',
  'f.alert.stock.rationed-against-empties': '{name}: crates only against empties',
  'f.alert.stock.low': '{name} is running low at the distributor',
  'f.alert.stock.available': '{name} is back in stock',
  'f.sch.skus': 'Products',
  'f.sch.allSkus': 'The whole order',
  'f.sch.threshold': 'Threshold',
  'f.sch.benefit': 'Benefit',
  'f.sch.valid': 'Valid',
  'f.sch.tiers': 'Outlet tiers',
  'f.sch.allTiers': 'All tiers',
  'f.sch.cooler': 'needs a company cooler',
  'f.sch.thrFree': '{n} cases in one order{pooled}',
  'f.sch.pooled': ', any mix',
  'f.sch.thrPct': '{n} cases or more in one order',
  'f.sch.thrFirst': 'First order within {days} days of registering',
  'f.sch.benFree': '{n} free case per threshold',
  'f.sch.benPct': '{pct}% off those lines',
  'f.sch.say': 'Say it to the retailer',
  'f.sch.sayText': '"{offer} The benefit comes through the distributor after the order, not on today\'s bill."',
  'f.sch.informational': 'Not applied at booking. Settlement: {who}',
  'f.sch.distributor': 'by the distributor',
  'f.stock.status': 'Status',
  'f.stock.ration': 'Ration',
  'f.stock.perOutlet': '{n} paid cases per outlet',
  'f.stock.note': 'Distributor note',
  'f.stock.sync': 'From the distributor\'s morning sync at {time}. Reliable for in or out of stock, not a promise of quantity through the day.',
  'f.stock.s.available': 'Available',
  'f.stock.s.low': 'Limited · running low',
  'f.stock.s.rationed': 'Limited · rationed',
  'f.stock.s.rationed-against-empties': 'Limited · against empties',
  'f.stock.s.out-of-stock': 'Out of stock',

  // targets
  'f.target.eyebrow': 'Priority target this season',
  'f.target.achieved': 'Placed',
  'f.target.target': 'Target',
  'f.target.remaining': 'To go',
  'f.target.daysLeft': 'Days left',
  'f.target.pace': 'About {n} cases a day gets you there by {date}.',
  'f.target.done': 'Target reached. Every extra case now builds your lead.',
  'f.target.measure': '{measure} ({skus}). Target: {basis}.',
  'f.rank.line': '#{rank} of {total} in {district} on pre-season placement',

  // assistant line
  'f.assist.label': 'Next step',
  'f.assist.progress': '{n} of {total} route outlets ordered today, {focus} with focus SKUs.',
  'f.assist.milestone': 'Pre-season is past {pct}%.',
  'f.assist.next': 'Next on your route: {name} (stop {stop}).',
  'f.assist.open': 'Open outlet',
  'f.assist.allDone': 'Route done for today. Clock out when you finish.',

  // leaderboard
  'f.lb.title': 'Leaderboard',
  'f.lb.yourPlace': 'Your place this pre-season',
  'f.lb.of': 'of {n} reps',
  'f.lb.gap': '{gap} points behind {name} on pre-season placement.',
  'f.lb.top': 'You lead the district on pre-season placement.',
  'f.lb.ranked': 'Ranked by pre-season placement',
  'f.lb.you': '{name} (you)',
  'f.lb.outlets': '{n} outlets',
  'f.lb.defs': 'What the numbers mean',
  'f.lb.note': 'Ranked on placement against each rep\'s own target, not raw cases, because territories differ. Your row updates as you book. Other reps\' figures are demo data.',
  'f.lb.short.preSeasonPct': 'Pre-season',
  'f.lb.short.productiveCallsPct': 'Productive calls',
  'f.lb.short.activeOutletsPct': 'Active outlets',
  'f.lb.short.focusCoveragePct': 'Focus SKU reach',
  'f.lb.short.monthTargetPct': 'April target',
  'f.lb.short.casesOrdered': 'Cases',

  // outlet tools
  'f.tools.label': 'Outlet actions',
  'f.tools.call': 'Call',
  'f.tools.note': 'Note',
  'f.tools.issue': 'Issue',
  'f.tools.addNote': 'Add note',
  'f.call.title': 'Call {name}',
  'f.call.owner': 'the owner',
  'f.call.demoNumber': 'Demo: no phone number on file',
  'f.call.ask': 'Ask if {owner} is at the shop and whether it is open today.',
  'f.call.usual': 'You usually reach here around {time}. Confirm that suits them.',
  'f.call.next': 'If today does not work, the next planned visit is {date}.',
  'f.call.log': 'After the call, tap what you found out. It is saved as a note.',
  'f.call.dial': 'Call now',
  'f.call.dialDemo': 'Call (demo: will not dial)',
  'f.call.noNumber': 'Demo: dialling is off because there is no real number on file',
  'f.call.present': 'Owner is there · coming today',
  'f.call.closed': 'Shop closed today',
  'f.call.later': 'Call back later',
  'f.call.note.present': 'Called ahead: owner at the shop, visit confirmed.',
  'f.call.note.closed': 'Called ahead: shop closed today.',
  'f.call.note.later': 'Called ahead: asked to call back later.',
  'f.note.title': 'Add a note',
  'f.note.label': 'What should you remember about {name}?',
  'f.note.ph': 'e.g. Cooler full at 9 am; owner wants 2-litre bottles for the weekend',
  'f.note.speak': 'Speak the note',
  'f.note.listening': 'Listening… tap to stop',
  'f.note.noVoice': 'Voice input is not available in this browser. Type the note instead.',
  'f.note.micBlocked': 'Microphone blocked. Type the note instead.',
  'f.note.micFail': 'Could not hear that. Try again or type the note.',
  'f.note.save': 'Save note',
  'f.note.saved': 'Note saved',
  'f.note.voice': 'voice',
  'f.note.call': 'call',
  'f.issue.title': 'Report a retailer issue',
  'f.issue.label': 'What is {name} unhappy about?',
  'f.issue.ph': "e.g. Free case from March scheme still not received",
  'f.issue.category': 'Category',
  'f.issue.auto': 'The category is guessed from the words you type. Tap another one if it is wrong.',
  'f.issue.save': 'Save issue',
  'f.issue.saved': 'Issue saved · {cat}',
  'f.issue.badge': { one: '1 open issue', other: '{n} open issues' },
  'f.issue.listTitle': 'Issues · {name}',
  'f.issue.resolve': 'Mark resolved',
  'f.issue.resolved': 'Resolved',
  'f.issue.cat.scheme': 'Scheme settlement',
  'f.issue.cat.quality': 'Product quality',
  'f.issue.cat.delay': 'Delayed order',
  'f.issue.cat.missing': 'Missing or damaged',
  'f.issue.cat.billing': 'Pricing or billing',
  'f.issue.cat.other': 'Other',
  'f.terr.pill': "{name}'s outlet",
  'f.terr.title': 'Outside your territory',
  'f.terr.body': "{name} belongs to {rep} ({territory}).",
  'f.terr.incentive': 'Cross-territory orders count {pct}% towards your incentive. The rest goes to the outlet\'s own rep.',
  'f.terr.go': 'Book anyway at {pct}% credit',
  'f.terr.back': 'Go back',
  'f.soh.title': 'Estimated stock on hand',
  'f.soh.sum': '~{n} cases',
  'f.soh.none': 'No estimate',
  'f.soh.delivered': '{n} delivered {date}',
  'f.soh.counted': 'Counted',
  'f.soh.conf.high': 'High confidence',
  'f.soh.conf.medium': 'Medium',
  'f.soh.conf.low': 'Low confidence',
  'f.soh.method': 'Estimated, not counted: last delivery minus modelled sales since then. Confidence falls as the delivery gets older. {counted} SKUs use your shelf count instead.',
};
