# Persona sheet copy, in two layers.
#   Top    = the TYPE of outlet: true of most outlets like it. No shop-specific dates, counts or ₹ (ranges are fine).
#   Boxed  = EXAMPLE IN OUR DATA: the demo shop. Every number there is read from data/ and
#            docs/validation/summary.json by build.py (order-date method, the app's own).
# Concern tags point to research Table G (why demand goes unmet); "§1"/"§3" = Industry_Context sections.

ROLES = {
    'helps-most': ('Helps most', '#56642f'),
    'handle-with-care': ('Handle with care', '#9b1c23'),
    'stays-quiet': ('Stays quiet', '#6b5d52'),
    'own-calendar': ('Own calendar', '#8a5512'),
    'thin-data': ('Thin data', '#3f5566'),
}

TABLE_G = {
    'G1': 'not chilled', 'G2': 'orders sized on last week', 'G3': 'distributor short', 'G4': 'credit and cash limits',
    'G5': 'not visited in time', 'G6': 'wrong pack', 'G7': 'won’t load up after leftovers', 'G8': 'margin elsewhere',
    'G9': 'scheme not trusted', 'G10': 'app friction', '§1': 'bought elsewhere', '§3': 'trust in the rep',
}

PERSONAS = [
    dict(no=1, id='OUT-01', file='P01-Flagship', label='The Flagship Kirana', role='helps-most', primary=True,
         definition='Busy main-road kiranas (₹3–10 lakh a month) with a company cooler; top tier, visited weekly.',
         also='Self-service mini-marts.',
         quote='Tell me the scheme first. Then I’ll stock up for summer.',
         driver='Heat', lift='≈ 2.5–3.0× January',
         concerns=[('Stocking up in time: orders follow last week, not the coming heat', 'G2'),
                   ('Clear scheme terms before committing to a big order', 'G9'),
                   ('Best seller short at the distributor right at the peak', 'G3'),
                   ('Cooler space, and buyers lost to the shop opposite', 'G1')],
         goals=['Stock up before the rush, not after', 'Earn the scheme’s free cases'],
         frustrations=['Scheme terms that arrive late or change', 'Rationed packs just when demand peaks'],
         buy=['Weekly, planned with a trusted rep', 'Chilled single-serve plus take-home packs'],
         needs=['When to stock up, and how much', 'A substitute that fits the cooler'],
         fires='forward baseline, pace gap, missing regular, threshold, distributor short',
         silent='credit headroom, no cooler',
         sees='Heat and a long weekend ahead: order for next week, not last week. You’re one case short of a free case.',
         based='brief · Industry_Context §3 · research Tables C, D, F, G · sample only as a realism check',
         confidence='High', check='5 rep ride-alongs at main-road kiranas in peak week; the bottler’s weekly sales by beat'),

    dict(no=2, id='OUT-02', file='P02-Cautious', label='The Cautious Kirana', role='handle-with-care', primary=False,
         definition='Small lane kiranas with no cooler and a low tier, selling mostly take-home bottles on tight cash.',
         also='Neighbourhood kiranas under ₹1 lakh a month (the brief’s own example).',
         quote='Last summer I sold the leftover big bottles at a loss. Give me only what will sell.',
         driver='Heat, muted', lift='≈ 1.6–2.0× January',
         concerns=[('Won’t load up after a season of leftovers and expiry', 'G7'),
                   ('Cash, credit and dues cap every order', 'G4'),
                   ('250 ml buyers go to shops that have a cooler', 'G1'),
                   ('Trusts the rep’s numbers less after a bad season', '§3')],
         goals=['Sell out before stock expires', 'Keep credit under control'],
         frustrations=['Leftovers sold at a loss', 'Losing cold-drink buyers to other shops'],
         buy=['Small orders, sized on recent sales', 'Mostly 2.25 L and 1.25 L bottles'],
         needs=['Small, safe quantities', 'Credit room shown to the rep only'],
         fires='credit headroom (rep only), safe cap, no cooler, not eligible',
         silent='pace gap and threshold nudges while dues are open (often fully silent)',
         sees='Suggest take-home packs only. Credit room is shown to you, not on the owner’s screen.',
         based='brief (Step 3 example) · Industry_Context §3 · research Tables D, G · sample only as a realism check',
         confidence='High', check='5 ride-alongs at no-cooler lane kiranas; distributor records of dues against order size'),

    dict(no=3, id='OUT-03', file='P03-ColdDrink', label='The Cold-Drink Shop', role='helps-most', primary=True,
         definition='Chilled-first impulse shops near colleges, offices and transit points.',
         also='Juice shops.',
         quote='Summer is my whole year. If the drinks aren’t cold, customers walk to the next shop.',
         driver='Heat, steepest', lift='≈ 3.5–4.5× January',
         concerns=[('Keeping drinks cold: cooler space and afternoon power cuts', 'G1'),
                   ('Running out before the next visit on hot weekends', 'G2'),
                   ('Peak packs rationed by the distributor', 'G3'),
                   ('Scheme uses used up early in the month', 'G9')],
         goals=['Full, cold coolers all day', 'Enough stock for hot weekends'],
         frustrations=['Warm coolers after power cuts', 'Best sellers rationed at the peak'],
         buy=['Weekly, planned for the coming week', 'Mostly single-serve: 250 ml, cans, energy'],
         needs=['An order that fits the coolers, plus back-stock', 'Which packs to chill first'],
         fires='cooler cap, distributor short, threshold (uses gone), pace gap',
         silent='credit headroom',
         sees='This month’s free cases are used up. Order what both coolers hold, plus back-stock to the next visit.',
         based='Industry_Context §3 · research Tables D, F, G · sample only as a realism check',
         confidence='Medium', check='cooler temperature logs and MSEDCL outage records; weekend stock counts at 5 cold-drink shops'),

    dict(no=4, id='OUT-04', file='P04-SnackStall', label='The Lakeside Snack Stall', role='thin-data', primary=False,
         definition='Footfall-led stalls at lakes, tourist spots and highways; lowest tier, monthly visits, an ice box, mostly cash.',
         also='Paan and tea stalls; highway dhabas on long weekends.',
         quote='On a summer Sunday I sell more than a whole winter week. Then I run out.',
         driver='Heat × weekends and holidays', lift='≈ 3–5× January on peak weekends',
         concerns=[('Runs out long before the next visit', 'G5'),
                   ('A peak order bigger than the credit limit', 'G4'),
                   ('No proper cooler; an ice box holds very little', 'G1'),
                   ('Restocks at the wholesale market, so we see only part of demand', '§1')],
         goals=['Stock that lasts to the next visit', 'Cold drinks on crowded days'],
         frustrations=['Running out on the best weekends', 'Paying cash above a small limit'],
         buy=['Once a month, sized on last month', 'Cash above the limit; tops up elsewhere'],
         needs=['An order that lasts the month', 'Estimates labelled as estimates'],
         fires='thin history, event ahead (1–3 May), credit headroom, cooler cap (ice box); the order must last ≈ 28 days',
         silent='trend claims from single-digit counts',
         sees='Long weekend ahead and the next visit is four weeks away. This is an estimate; anything over the limit is cash.',
         based='Industry_Context §1, §3 · research Tables C, D, F, G · sample only as a realism check',
         confidence='Medium', check='ride-alongs on two peak weekends; wholesale-market purchases by 5 stalls'),

    dict(no=5, id='OUT-05', file='P05-SchoolCanteen', label='The School Canteen', role='stays-quiet', primary=False,
         definition='Outlets whose season follows an institution’s calendar: school and college canteens.',
         also='College canteens and hostel-belt shops.',
         quote='Exams first, then the holidays. Small quantities till the school shuts, please.',
         driver='The school calendar, not heat', lift='≈ 1.2× in April; ≈ 0 in the vacation',
         concerns=[('Leftovers sitting through a long closure', 'G7'),
                   ('A range limited by school rules', 'G6'),
                   ('Restocking in time for reopening', 'G5'),
                   ('Wasted visits while the school is shut', 'G5')],
         goals=['No stock left at closure', 'Restock just before reopening'],
         frustrations=['Summer pushes that don’t fit a school', 'Visits while it’s shut'],
         buy=['Small orders around term and exams', 'Water and mango drinks, within school rules'],
         needs=['Order less before closing', 'Never suggest what school rules exclude'],
         fires='closing soon (first in rule order)',
         silent='pace gap, threshold, event ahead',
         sees='Closing soon: order only what sells before the school shuts.',
         based='research Tables C, D (school dates: Lokmat Times, 30 Mar 2026) · school rules · sample only as a realism check',
         confidence='High', check='school calendars for the beat; interviews with 3 canteen contractors'),

    dict(no=6, id='OUT-06', file='P06-BanquetHall', label='The Banquet Hall', role='own-calendar', primary=False,
         definition='Event-led outlets: banquet halls, wedding lawns and caterers.',
         also='Cinemas; dhabas in the wedding season.',
         quote='Show me the bookings and I’ll tell you the cases.',
         driver='Bookings × weather', lift='≈ 1–3×; no wedding dates 17 May – 15 Jun 2026 (adhik month)',
         concerns=[('The right stock a day before each event', 'G5'),
                   ('Credit too small for peak wedding weeks', 'G4'),
                   ('Heat-based advice that ignores the bookings', 'G2'),
                   ('Last-minute gaps when guest numbers change', 'G2')],
         goals=['The right stock before every event', 'Enough credit for peak weeks'],
         frustrations=['Advice based on heat, not bookings', 'Limits too small for wedding weeks'],
         buy=['Event by event, from the booking calendar', 'Big packs and water for guests'],
         needs=['Cases for each booked event', 'Credit room for the busy weeks'],
         fires='event ahead (bookings), missing regular, larger than usual (legitimate here), credit headroom',
         silent='heat-based pace gap',
         sees='Bookings before the next visit need more than usual, and that’s expected. The order is over the credit limit.',
         based='research Tables C, D, G · Hindu Panchang (adhik month) · sample only as a realism check',
         confidence='Medium', check='booking calendars from 5 halls; caterers’ cases per 100 guests'),

    dict(no=7, id='OUT-07', file='P07-Wholesaler', label='The Beverage Wholesaler', role='stays-quiet', primary=False,
         definition='Wholesalers who sell on to other shops, some off the route; big packs, deal-driven, top tier by volume.',
         also='Sub-stockists and market traders who sell on.',
         quote='At month-end, give me the big packs at a good rate. I’ll move them.',
         driver='Trade deals and month-end targets', lift='≈ 2–3×, bought ahead of the shops',
         concerns=[('The best rate on big packs', 'G8'),
                   ('Fast booking, with no extra screens', 'G10'),
                   ('Stock limits known up front', 'G3'),
                   ('Deals honoured, and a large credit line with dues', 'G4')],
         goals=['The best rate on big packs', 'Quick, simple booking'],
         frustrations=['Slow ordering', 'Deals not honoured'],
         buy=['Big packs at month-end, ahead of the shops', 'Cash on deals; a large credit line'],
         needs=['Plain, fast booking', 'Stock limits up front'],
         fires='silence (no season advice)',
         silent='season state, pace gap, event ahead, nudges',
         sees='Nothing beyond the distributor’s stock limits.',
         based='Industry_Context §3 · research Tables D, G · sample only as a realism check',
         confidence='Medium', check='distributor invoices showing where wholesaler volume goes; month-end order logs'),

    dict(no=8, id='OUT-08', file='P08-NewOwner', label='The New Owner', role='thin-data', primary=False,
         definition='Any outlet with no usable history: new, or a new owner under a new code; most often a small kirana.',
         also='Newly opened and re-coded outlets.',
         quote='I’m new here. How much cola should I keep for summer?',
         driver='Unknown; borrowed from similar shops', lift='≈ 1.6× (est., from similar shops)',
         concerns=[('No numbers to plan with', 'G2'),
                   ('Fear of over-ordering', 'G7'),
                   ('Doesn’t know the schemes yet', 'G9'),
                   ('Trust with the rep still to build', '§3')],
         goals=['Know what to stock for summer', 'Avoid leftovers'],
         frustrations=['Guesswork on quantities', 'Schemes nobody has explained'],
         buy=['A small first order, then top-ups', 'Watches what sells before committing'],
         needs=['A starting estimate, labelled as one', 'A planned top-up at the next visit'],
         fires='thin history (estimate from peers.json, labelled), no cooler, not eligible',
         silent='missing regular',
         sees='No history yet. This estimate comes from similar shops nearby: start small and top up next visit.',
         based='research Tables D, G · peers.json (similar shops, est.) · sample only as a realism check',
         confidence='Medium', check='the first 3 orders of new outlets against the peer estimate'),
]

# Overview: type map (season set by · cold storage · cash room · visits · history · owner)
TYPE_MAP = {
    1: ('Heat', 'Company cooler', 'Ample', 'Weekly', 'Rich', 'Plans with the rep'),
    2: ('Heat, muted', 'None', 'Tight, with dues', 'Fortnightly', 'Rich', 'Careful, wary'),
    3: ('Heat, steepest', 'Two coolers', 'Ample', 'Weekly', 'Rich', 'Plans for summer'),
    4: ('Heat × weekends', 'Ice box', 'Below a peak order', 'Monthly', 'Thin', 'Cash; buys elsewhere too'),
    5: ('School calendar', 'Small cooler', 'Ample', 'Every 10 days', 'Gaps', 'Follows the calendar'),
    6: ('Bookings', 'Small cooler', 'Short in peak weeks', 'Every 10 days', 'Event-led', 'Orders by bookings'),
    7: ('Trade deals', 'None', 'Large, with dues', 'Weekly', 'Misleading', 'Volume trader'),
    8: ('Unknown', 'None', 'Ample', 'Fortnightly', 'None', 'New and careful'),
}
