#!/usr/bin/env python3
"""
Builds the app as ONE file (CSS, JavaScript and an embedded copy of the data), written twice:
  gt-app.html  – double-click to use offline (reads the embedded copy)
  index.html   – the page GitHub Pages serves (reads data/*.json next to it)
Both files are identical; the page decides at run time where its data comes from.

Source: scripts/shell.html (page template), css/, js/ and data/.
Rerun this after changing any of them, from the project folder:

    python3 scripts/build_single.py

How it works: each ES module becomes one block, modules['ui'] = (() => { … return { … }; })(),
in dependency order, and its imports become  const { html, … } = modules['ui'];
Data files go at the bottom as <script type="application/json" id="data-config"> blocks,
which js/data.js reads before trying to fetch data/*.json.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JS = ROOT / "js"
OUTPUTS = [ROOT / "gt-app.html", ROOT / "index.html"]
SHELL = ROOT / "scripts" / "shell.html"
DATA_FILES = ["config", "outlets", "products", "schemes", "orders", "history", "visits",
              "distributor_stock", "calendar", "peers"]

IMPORT_NS = re.compile(r"""^import\s+\*\s+as\s+(\w+)\s+from\s+['"](.+?)['"];?\s*$""")
IMPORT_NAMED = re.compile(r"""^import\s+\{([^}]*)\}\s+from\s+['"](.+?)['"];?\s*$""")
EXPORT_DECL = re.compile(r"^export\s+((?:async\s+)?function\*?|const|let|class)\s+(\w+)")


def key_for(path: Path) -> str:
    return path.relative_to(JS).with_suffix("").as_posix()


def transform(path: Path):
    """→ (module source as a block, [dependency paths])"""
    deps, exports, lines = [], [], []
    for line in path.read_text(encoding="utf-8").splitlines():
        m_ns, m_named = IMPORT_NS.match(line), IMPORT_NAMED.match(line)
        if m_ns or m_named:
            spec = (m_ns or m_named).group(2)
            dep = (path.parent / spec).resolve()
            deps.append(dep)
            if m_ns:
                lines.append(f"const {m_ns.group(1)} = modules['{key_for(dep)}'];")
            else:
                names = ", ".join(n.strip().replace(" as ", ": ") for n in m_named.group(1).split(",") if n.strip())
                lines.append(f"const {{ {names} }} = modules['{key_for(dep)}'];")
            continue
        m_exp = EXPORT_DECL.match(line)
        if m_exp:
            exports.append(m_exp.group(2))
            line = line[len("export "):]
        if line.lstrip().startswith(("import ", "export ")) and not line.startswith((" ", "\t")):
            raise SystemExit(f"{path.relative_to(ROOT)}: can't bundle this line: {line}")
        lines.append(line)
    body = "\n".join(lines).rstrip()
    key = key_for(path)
    block = (f"/* {'=' * 20} js/{key}.js {'=' * 20} */\n"
             f"modules['{key}'] = (() => {{\n{body}\n\nreturn {{ {', '.join(exports)} }};\n}})();\n")
    return block, deps


# Walk imports from main.js; emit each module after its dependencies.
order, seen = [], set()


def visit(path: Path):
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)
    block, deps = transform(path)
    for d in deps:
        visit(d)
    order.append(block)


visit(JS / "main.js")

css = (ROOT / "css" / "styles.css").read_text(encoding="utf-8").rstrip()
page = SHELL.read_text(encoding="utf-8")

LINK = '<link rel="stylesheet" href="css/styles.css">'
SCRIPT = '<script type="module" src="js/main.js"></script>'
assert LINK in page and SCRIPT in page and "</body>" in page, "scripts/shell.html changed shape; update build_single.py"

data_blocks = []
missing = [n for n in DATA_FILES if not (ROOT / "data" / f"{n}.json").exists()]
if missing:
    raise SystemExit(f"data/ is missing required files: {', '.join(n + '.json' for n in missing)}")
for name in DATA_FILES:
    text = (ROOT / "data" / f"{name}.json").read_text(encoding="utf-8").strip().replace("</", "<\\/")   # never close the <script> early
    data_blocks.append(f'<script type="application/json" id="data-{name}">\n{text}\n</script>')

app_script = (
    '<script type="module">\n'
    "// GT App prototype: single-file build, generated by scripts/build_single.py.\n"
    "// Each block below is one file from js/. To change the app for good, edit js/ and rebuild.\n"
    "const modules = {};\n\n" + "\n".join(order) + "</script>"
)

page = page.replace(LINK, f"<style>\n{css}\n</style>")
page = page.replace(f"  {SCRIPT}\n", "").replace(SCRIPT, "")
page = page.replace(
    "</body>",
    f"{app_script}\n\n<!-- ==================== DATA (from data/*.json) ==================== -->\n"
    + "\n".join(data_blocks) + "\n</body>",
)
page = page.replace(
    "<!-- Build template for scripts/build_single.py (not a page to open). The built app is gt-app.html / index.html. -->",
    "<!-- GT App prototype · single file, BUILT by scripts/build_single.py from scripts/shell.html, css/, js/ and data/.\n"
    "     Don't edit this file: edit the source and rebuild. Served over http(s) it reads data/*.json;\n"
    "     opened from disk it reads the copy embedded at the bottom. -->", 1)

for out in OUTPUTS:
    out.write_text(page, encoding="utf-8")
size = OUTPUTS[0].stat().st_size / 1024
print(f"Wrote {' and '.join(o.name for o in OUTPUTS)}: {len(order)} modules, {len(data_blocks)} data files, {size:.0f} KB each")
